const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const deps=process.env.PRICE_TEST_MODULES;if(!deps)throw new Error('Set PRICE_TEST_MODULES');
const React=require(path.join(deps,'react')),Renderer=require(path.join(deps,'react-test-renderer'));global.IS_REACT_ACT_ENVIRONMENT=true;global.window={addEventListener(){},removeEventListener(){}};
const cache=new Map();function read(file){const name=path.resolve(file);if(cache.has(name))return cache.get(name).exports;const m=new Module(name,module);cache.set(name,m);m.paths=module.paths;const orig=m.require.bind(m);m.require=id=>{if(id==='react')return React;if(id==='react/jsx-runtime')return require(path.join(deps,'react/jsx-runtime'));if(id.startsWith('@/')||id.startsWith('.')){let p=id.startsWith('@/')?path.resolve(id.slice(2)):path.resolve(path.dirname(name),id);return read(fs.existsSync(p+'.tsx')?p+'.tsx':p+'.ts')}return orig(id)};m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020}}).outputText,name);return m.exports;}
const Editor=read('components/PriceEditor.tsx').default;const {defaults}=read('lib/defaults.ts');
async function main(){let view,saved,calls=0,fail=false;let prices=defaults.filter(x=>x.id==='paint_walls_sqft');const onSave=async p=>{calls++;if(fail)throw Error('Offline');saved=JSON.parse(JSON.stringify(p));return 'Saved'};await Renderer.act(async()=>{view=Renderer.create(React.createElement(Editor,{prices,onSave}))});
const button=label=>view.root.findAllByType('button').find(b=>b.children.join('')===label);const material=field=>view.root.findAllByType('input').find(i=>i.props['aria-label']===field);const status=()=>view.root.findAllByType('select').find(s=>s.props.value==='partial'||s.props.value==='priced');
await Renderer.act(async()=>material('materialRate').props.onChange({target:{value:'.30'}}));await Renderer.act(async()=>status().props.onChange({target:{value:'priced'}}));
await Renderer.act(async()=>view.update(React.createElement(Editor,{prices:prices.map(p=>({...p,materialRate:999})),onSave})));assert.equal(material('materialRate').props.value,.30,'dirty draft preserved');
await Renderer.act(async()=>material('materialMin').props.onChange({target:{value:''}}));await Renderer.act(async()=>button('Зберегти ціни').props.onClick());assert.equal(calls,0,'blank material cannot save');
await Renderer.act(async()=>material('materialMin').props.onChange({target:{value:'.21'}}));fail=true;await Renderer.act(async()=>button('Зберегти ціни').props.onClick());assert.equal(saved,undefined);assert.equal(material('materialRate').props.value,.30);fail=false;
await Renderer.act(async()=>button('Зберегти ціни').props.onClick());assert.equal(saved[0].materialMin,.21);assert.equal(saved[0].materialRate,.30);assert.equal(saved[0].materialStatus,'priced');
await Renderer.act(async()=>button('Повернути заводські ціни').props.onClick());const before=calls;await Renderer.act(async()=>button('Так, повернути').props.onClick());assert.equal(calls,before);await Renderer.act(async()=>button('Зберегти ціни').props.onClick());assert.deepEqual(saved,JSON.parse(JSON.stringify(defaults)));await Renderer.act(async()=>view.unmount());console.log('PASS material editor: edits, background refresh, blank rejection, save failure/retry, save serialization, explicit default reset');}
main().catch(e=>{console.error(e);process.exitCode=1});
