import type {CalcTask} from "./calcTypes";

/**
 * calcDefaults
 * ------------
 * The Calculator tab's editable labor/material pricing database — ported
 * from the standalone construction-estimator app's pricing-data.js.
 * Every rate is either a placeholder to edit for your own market, or a
 * rate calibrated against Homewyse.com's publicly displayed national
 * average figures (cited, with date, in each task's "source" field) —
 * never a copy of any proprietary per-ZIP calculator, branding, or
 * database.
 *
 * Users can edit every field from the Calculator tab's "Ціни калькулятора"
 * panel; edits are saved to this browser only (localStorage key
 * qc-calc-pricing-v1), same as the standalone app.
 */
export const calcDefaults:CalcTask[]=[

  // ---------------- FLOORING ----------------
  {id:"flooring_laminate_lvp_install",category:"Flooring",name:"Laminate / LVP Flooring Installation",unit:"sqft",laborRate:3.75,materialRate:3.50,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Includes standard underlayment and transitions. Does not include subfloor repair or self-leveling.",source:"Homewyse.com national average reference, May 2026 ($6.91–$11.81/sq ft installed)"},
  {id:"flooring_carpet_remove",category:"Flooring",name:"Carpet Removal & Disposal",unit:"sqft",laborRate:1.60,materialRate:0,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Includes carpet, pad, and tack strip removal and haul-away.",source:"Homewyse.com national average reference, May 2026 ($1.37–$2.49/sq ft)"},
  {id:"flooring_floor_prep_selfleveling",category:"Flooring",name:"Floor Prep / Self-Leveling Underlayment",unit:"sqft",laborRate:3.00,materialRate:1.70,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Standard localized leveling and adhesive removal. Does not include structural subfloor repair or major moisture remediation.",source:"Homewyse.com national average reference, May 2026 ($4.38–$5.27/sq ft underlayment)"},
  {id:"flooring_tile_floor_install",category:"Flooring",name:"Ceramic/Porcelain Floor Tile Installation",unit:"sqft",laborRate:7.5,materialRate:9.0,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standard-set tile, grout included. Waterproofing/membrane priced separately.",source:"Homewyse.com national average reference, Sep 2026 ($16.38-20.21/sq ft); cross-checked against Budget Construction Co. / Homeyou Chicago."},
  {id:"flooring_lvp_remove",category:"Flooring",name:"Remove Old Laminate / LVP Flooring",unit:"sqft",laborRate:1.75,materialRate:0.25,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and haul-away of existing flooring.",source:"Homewyse.com national average reference, Sep 2026 ($2.42-4.47/sq ft (general flooring removal)); cross-checked against Angi / Budget Construction Chicago."},

  // ---------------- TRIM ----------------
  {id:"trim_baseboard_install",category:"Trim",name:"Baseboard Installation",unit:"linear_ft",laborRate:7.50,materialRate:2.80,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard MDF baseboard, caulked and nail holes filled, unpainted.",source:"Homewyse.com national average reference, May 2026 ($8.96–$13.71/linear ft)"},
  {id:"trim_shoe_molding_install",category:"Trim",name:"Shoe Molding Installation",unit:"linear_ft",laborRate:3.0,materialRate:1.0,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Installed alongside new flooring, caulked, unpainted.",source:"Homewyse.com national average reference, Sep 2026 ($7.58-11.60/linear ft (general molding proxy)); cross-checked against Contractor+ Chicago."},
  {id:"trim_door_casing_install",category:"Trim",name:"Door Casing Installation",unit:"linear_ft",laborRate:6.0,materialRate:2.0,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard door trim, one side.",source:"Homewyse.com national average reference, Sep 2026 ($7.92-12.14/linear ft); cross-checked against Contractor+ Chicago."},
  {id:"trim_baseboard_remove",category:"Trim",name:"Remove Existing Baseboard",unit:"linear_ft",laborRate:2.0,materialRate:0.0,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and disposal of existing baseboard.",source:"Homewyse.com national average reference, Sep 2026 ($1.11-2.25/linear ft); cross-checked against no Chicago source found."},
  {id:"trim_caulk_finish",category:"Trim",name:"Caulking & Finish Work",unit:"linear_ft",laborRate:1.75,materialRate:0.3,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.15},lowMult:0.85,highMult:1.25,notes:"Caulking baseboard, casing, and trim seams; filling nail holes.",source:"Homewyse.com national average reference, Sep 2026 ($2.45-5.03/linear ft (exterior caulk proxy)); cross-checked against no Chicago source found."},

  // ---------------- DRYWALL ----------------
  {id:"drywall_install",category:"Drywall",name:"Drywall Installation (hang, tape, mud, sand)",unit:"sqft",laborRate:1.90,materialRate:0.60,suppliesPct:0.08,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"New drywall hung, taped, mudded, and sanded — ready to prime and paint.",source:"Homewyse.com national average reference, May 2026 ($2.26–$2.69/sq ft)"},
  {id:"drywall_repair",category:"Drywall",name:"Drywall Repair (patch, hole, or small area)",unit:"each",laborRate:300,materialRate:35,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.25,notes:"One patch or hole, mudded, sanded, ready to paint. Priced per repair, not per square foot.",source:"Homewyse.com national average reference, May 2026 ($297–$472 per repair)"},
  {id:"drywall_insulation_wall",category:"Insulation",name:"Wall Insulation Installation",unit:"sqft",laborRate:1.20,materialRate:1.10,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard batt insulation in open wall cavities, before drywall.",source:"Homewyse.com national average reference, May 2026 ($1.87–$3.03/sq ft)"},
  {id:"drywall_new_wall_frame",category:"Drywall",name:"New Stud Wall Framing",unit:"linear_ft",laborRate:13.0,materialRate:5.5,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Wood or metal stud partition wall framing, priced per linear foot of wall.",source:"Homewyse.com national average reference, Sep 2026 ($3.88-6.62/sq ft face (~$31-53/lf at 8ft)); cross-checked against Angi Chicago."},
  {id:"drywall_finish_sqft",category:"Drywall",name:"Drywall Finishing (tape, mud, sand only)",unit:"sqft",laborRate:1.57,materialRate:0.28,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Tape, mud (2-3 coats) and sand new or patched seams -- finishing step only, does not include hanging the board.",source:"Homewyse.com national average reference, Sep 2026 ($1.20-2.90/sq ft by finish level); cross-checked against Angi Chicago ($0.95-2.90/sq ft)."},
  {id:"drywall_remove_sqft",category:"Drywall",name:"Remove Damaged Drywall",unit:"sqft",laborRate:1.25,materialRate:0.22,suppliesPct:0.08,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Cut out and haul away damaged gypsum board; no new board or finish included.",source:"Homewyse.com national average reference, Sep 2026 ($1.04-1.89/sq ft); cross-checked against Angi Chicago ($0.50-2.90/sq ft panel/plaster removal)."},
  {id:"drywall_crack_linear_ft",category:"Drywall",name:"Repair Drywall Crack",unit:"linear_ft",laborRate:1.53,materialRate:0.27,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Rout crack, mesh tape, 2 coats compound, sand; small jobs may hit the minimum price floor.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per standalone crack repair); cross-checked against Angi Chicago ($305-905 per repair job, avg $604)."},
  {id:"drywall_tape_repair_each",category:"Drywall",name:"Repair Loose Drywall Tape Seam",unit:"each",laborRate:165,materialRate:25,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Cut out failed tape seam (~2-3 ft), re-tape, 2-3 coats compound, sand -- single spot repair.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per standalone repair call, scaled for tape-only scope); cross-checked against Homeyou.com Chicago ($284 avg per patch)."},
  {id:"drywall_corner_repair_each",category:"Drywall",name:"Repair Damaged Drywall Corner",unit:"each",laborRate:180,materialRate:30,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Remove damaged corner bead (~3-4 linear ft), install new bead, 2-3 coats compound, sand.",source:"Homewyse.com national average reference, Sep 2026 ($4.06-4.89/linear ft corner bead plus finishing labor); cross-checked against Angi Chicago (drywall specialist rate ~$90/hr)."},
  {id:"drywall_patch_addon_minor",category:"Drywall",name:"Minor Drywall Patch (Add-on)",unit:"each",laborRate:78,materialRate:17,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Small nail/anchor hole patch (under 3in), done as an add-on during an in-progress repaint job -- no separate trip charge.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 standalone repair call, reduced for add-on/no-trip-charge scope); cross-checked against Angi Chicago (small-hole fix $25-125 each)."},
  {id:"drywall_patch_addon_medium",category:"Drywall",name:"Medium Drywall Patch (Add-on)",unit:"each",laborRate:185,materialRate:27,suppliesPct:0.08,suppliesFixed:0,minPrice:125,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Medium hole (~1-4 sq ft) patch/tape/mud/sand added during a repaint visit -- no separate trip charge, ~2 hrs on-site.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per standalone patch); cross-checked against Homeyou Chicago ($284/patch: ~$260 labor + $24 materials), discounted ~25% for bundled add-on."},
  {id:"drywall_patch_addon_large",category:"Drywall",name:"Large Drywall Repair (Add-on)",unit:"each",laborRate:300,materialRate:65,suppliesPct:0.08,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.25,notes:"Larger damaged section (~5-10 sq ft) replaced as an add-on during painting -- ~3-3.5 hrs on-site plus extra mud/tape/scrap drywall.",source:"Homewyse.com national average reference, Sep 2026 ($297-472/patch base scaled to $300-650 for larger bundled sections); cross-checked against Angi Chicago ($1,040-1,560 for a standalone 20 sq ft repair) scaled down for a smaller bundled add-on."},
  {id:"drywall_repair_standalone",category:"Drywall",name:"Standalone Drywall Repair Visit",unit:"each",laborRate:335,materialRate:50,suppliesPct:0.08,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standalone small-patch service call including trip/minimum-labor charge (~3.5-4 hrs), separate from any painting job.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per patch); cross-checked against Angi Chicago ($604 avg per standalone project, most $305-905; handyperson $60/hr, specialist $90/hr)."},
  {id:"insulation_drywall_package_each",category:"Insulation",name:"Insulation + Drywall Installation Package",unit:"each",laborRate:840,materialRate:560,suppliesPct:0.10,suppliesFixed:0,minPrice:800,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Bundled job for a typical ~300 sq ft of wall area: install open-cavity batt insulation, then hang/tape/mud/sand new drywall over it, per room/area.",source:"Homewyse.com national average reference, Sep 2026 ($3.93-5.45/sq ft combined, ~$1,180-1,635 for 300 sq ft); cross-checked against Angi Chicago ($1-4/sq ft insulation, whole-home avg $1,701, plus up to $600 for post-insulation drywall repair)."},

  // ---------------- PAINTING ----------------
  {id:"paint_room_floor_sqft",category:"Painting",name:"Interior Room Painting (walls & trim, per sq ft of floor area)",unit:"sqft",laborRate:5.00,materialRate:1.30,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Two coats, walls and trim, lightly-textured surfaces. Quantity = room FLOOR area, not wall area (matches how most painters quote a whole room).",source:"Homewyse.com national average reference, May 2026 ($4.22–$8.19/sq ft of floor area)"},
  {id:"paint_wall_sqft",category:"Painting",name:"Paint Wall (per sq ft of wall surface)",unit:"sqft",laborRate:1.9,materialRate:0.4,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats, priced per sq ft of actual wall surface — use this instead of the per-floor-sqft room rate when you're only painting specific walls.",source:"Homewyse.com national average reference, Sep 2026 ($1.29-2.78/sq ft); cross-checked against Angi Chicago."},
  {id:"paint_ceiling_sqft",category:"Painting",name:"Paint Ceiling",unit:"sqft",laborRate:2.0,materialRate:0.4,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"One coat ceiling paint, standard height.",source:"Homewyse.com national average reference, Sep 2026 ($1.37-2.95/sq ft); cross-checked against Angi Chicago."},
  {id:"paint_trim_linear_ft",category:"Painting",name:"Paint Baseboards & Trim",unit:"linear_ft",laborRate:2.15,materialRate:0.35,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats on baseboard and door/window trim.",source:"Homewyse.com national average reference, Sep 2026 ($1.60-3.39/linear ft (Paint Trim Molding)); cross-checked against Angi Chicago."},
  {id:"paint_door_each",category:"Painting",name:"Paint Door (both sides)",unit:"each",laborRate:160,materialRate:30,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats, both faces, hardware masked or removed.",source:"Homewyse.com national average reference, Sep 2026 ($163-332/door); cross-checked against Contractor+ Chicago."},
  {id:"water_stain_block_each",category:"Painting",name:"Seal Water Stain (Stain-Blocking Primer)",unit:"each",laborRate:75,materialRate:18,suppliesPct:0.05,suppliesFixed:0,minPrice:60,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Spot-prime a small water-stain area (~4-9 sq ft) with stain-blocking primer before repainting -- minor add-on to a paint job.",source:"Homewyse.com national average reference, Sep 2026 (closest match 'Cost to Paint Wall', $1.29-2.78/sq ft, primer as job-supply line); cross-checked against Angi Chicago interior-painting guide (prep/patch $0.50-0.75/sq ft, primer ~$10/quart per 100 sq ft)."},
  {id:"paint_repaired_areas_each",category:"Painting",name:"Prime and Paint Repaired Areas",unit:"each",laborRate:310,materialRate:70,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes a patch up to ~4 sq ft: spot-prime plus 2 coats blended into the surrounding wall after a drywall repair -- per patch, not a full wall.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per patch); cross-checked against Homeyou Chicago."},
  {id:"paint_baseboard_shoe_package_each",category:"Painting",name:"Paint Baseboards & Shoe Molding Package",unit:"each",laborRate:160,materialRate:40,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes ~40 linear ft typical room perimeter; baseboards plus shoe molding together, prep/caulk and 2 coats.",source:"Homewyse.com national average reference, Sep 2026 ($2.30-4.88/linear ft baseboard basis); cross-checked against Homeyou Chicago ($2-4/linear ft trim)."},
  {id:"paint_door_frame_each",category:"Painting",name:"Paint Door Frame",unit:"each",laborRate:65,materialRate:15,suppliesPct:0.05,suppliesFixed:0,minPrice:60,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes ~17 linear ft of frame/casing per standard interior door opening, 2 coats -- not the door slab itself.",source:"Homewyse.com national average reference, Sep 2026 ($2.37-5.02/linear ft, ~$40-85/frame); cross-checked against Angi Chicago painting labor rates ($50-75/hr)."},
  {id:"paint_baseboards_linear_ft",category:"Painting",name:"Paint Baseboards (Only)",unit:"linear_ft",laborRate:2.60,materialRate:0.65,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Baseboards only, no shoe molding; standard prep, 2 coats.",source:"Homewyse.com national average reference, Sep 2026 ($2.30-4.88/linear ft); cross-checked against Homeyou Chicago ($2-4/linear ft)."},
  {id:"paint_window_each",category:"Painting",name:"Paint Window",unit:"each",laborRate:95,materialRate:20,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes ~20 linear ft of sash/frame/trim per standard window, masking of glass, 2 coats.",source:"Homewyse.com national average reference, Sep 2026 ($3.72-7.69/linear ft, ~$75-155/window); cross-checked against Angi Chicago interior-painting labor rates ($50-75/hr)."},
  {id:"paint_wall_each",category:"Painting",name:"Paint One Wall",unit:"each",laborRate:168,materialRate:42,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Typical ~10x8 wall (80 sq ft), 2 coats, standard prep.",source:"Homewyse.com national average reference, Sep 2026 ($1.29-2.78/sq ft, ~$103-222/wall at 80 sq ft); cross-checked against Angi Chicago room-painting guide ($2.50-5/sq ft)."},
  {id:"paint_room",category:"Painting",name:"Paint Room Walls (Flat Rate)",unit:"room",laborRate:760,materialRate:190,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Typical bedroom ~129 sq ft of wall area (walls only), standard prep, 2 coats, no ceiling.",source:"Homewyse.com national average reference, Sep 2026 ($4.22-8.19/sq ft, ~$544-1057/room); cross-checked against Angi Chicago room-painting guide (avg $1,140, range $414-1,658)."},

  // ---------------- DOORS ----------------
  {id:"door_install_interior",category:"Doors",name:"Install Interior Door (prehung)",unit:"each",laborRate:350,materialRate:180,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard prehung interior door with hardware.",source:"Homewyse.com national average reference, May 2026 ($444–$675 per door)"},
  {id:"door_remove_interior",category:"Doors",name:"Remove Interior Door",unit:"each",laborRate:90,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:90,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and disposal of existing door and frame if needed.",source:"Homewyse.com national average reference, Sep 2026 ($19.43-33.25 (slab-only)); cross-checked against no Chicago source found."},

  // ---------------- BATHROOM ----------------
  {id:"bath_vanity_install",category:"Bathroom",name:"Install Bathroom Vanity",unit:"each",laborRate:280,materialRate:60,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Set and secure vanity cabinet; plumbing connection priced separately.",source:"Homewyse.com national average reference, Sep 2026 ($576-871); cross-checked against Angi Chicago."},
  {id:"bath_toilet_replace",category:"Bathroom",name:"Remove & Install Toilet",unit:"each",laborRate:160,materialRate:230,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard two-piece toilet, wax ring and supply line included.",source:"Homewyse.com national average reference, Sep 2026 ($707-1238); cross-checked against Angi Chicago."},
  {id:"bath_faucet_replace",category:"Bathroom",name:"Replace Bathroom Faucet",unit:"each",laborRate:150,materialRate:110,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Standard single-hole faucet swap.",source:"Homewyse.com national average reference, Sep 2026 ($511-717); cross-checked against Angi Chicago (kitchen proxy)."},
  {id:"bath_tile_wall_install",category:"Bathroom",name:"Install Wall Tile (shower/tub surround)",unit:"sqft",laborRate:9.5,materialRate:10.5,suppliesPct:0.06,suppliesFixed:0,minPrice:500,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Standard-set wall tile with waterproofing membrane priced separately.",source:"Homewyse.com national average reference, Sep 2026 ($11.48-21.27/sq ft); cross-checked against Angi / DoItOrHire Chicago."},

  // ---------------- KITCHEN ----------------
  {id:"kitchen_cabinet_install",category:"Kitchen",name:"Install Kitchen Cabinet (per unit)",unit:"each",laborRate:130,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:130,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Labor to set and secure one pre-built cabinet box. Cabinet cost priced separately as material.",source:"Homewyse.com national average reference, Sep 2026 ($486-736 (bundled material)); cross-checked against Homeyou Chicago."},
  {id:"kitchen_countertop_install",category:"Kitchen",name:"Install Countertop",unit:"linear_ft",laborRate:25,materialRate:50,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standard laminate/butcher-block countertop, priced per linear foot. Stone/quartz will run considerably higher — adjust materialRate.",source:"Homewyse.com national average reference, Sep 2026 ($41.94-63.77/sq ft (laminate)); cross-checked against SlabWise Chicago."},
  {id:"kitchen_faucet_replace",category:"Kitchen",name:"Replace Kitchen Faucet",unit:"each",laborRate:165,materialRate:120,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Standard single-hole kitchen faucet swap.",source:"Homewyse.com national average reference, Sep 2026 ($539-861); cross-checked against Angi Chicago."},

  // ---------------- DEMOLITION & CLEANUP ----------------
  {id:"demo_general_sqft",category:"Demolition",name:"General Interior Demolition",unit:"sqft",laborRate:2.0,materialRate:0.15,suppliesPct:0.10,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Non-structural demolition of finishes (drywall, trim, flooring).",source:"Homewyse.com national average reference, Sep 2026 ($1.04-1.89/sq ft (wallboard removal proxy)); cross-checked against Homeyou Chicago."},
  {id:"demo_debris_haul_each",category:"Demolition",name:"Debris Haul-Away",unit:"each",laborRate:0,materialRate:0,suppliesPct:0,suppliesFixed:300,minPrice:300,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.3},lowMult:0.9,highMult:1.35,notes:"Loading and hauling construction debris to disposal. Scales with dumpster/truckloads needed — add more than one unit for larger jobs.",source:"Homewyse.com national average reference, Sep 2026 ($70.51-82.61/cu yd); cross-checked against GoLoadUp Chicago."},
  {id:"demo_final_cleanup_room",category:"Demolition",name:"Final Job-Site Cleanup",unit:"room",laborRate:110,materialRate:10,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.2},lowMult:0.9,highMult:1.2,notes:"Broom-clean and wipe-down at project completion.",source:"Homewyse.com national average reference, Sep 2026 ($119-153/room); cross-checked against Angi Chicago."},
  {id:"demo_protect_room",category:"Demolition",name:"Protect Floors & Furniture",unit:"room",laborRate:100,materialRate:25,suppliesPct:0.10,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.1},lowMult:0.9,highMult:1.2,notes:"Floor protection film/paper and furniture covering for the duration of the job.",source:"Homewyse.com national average reference, Sep 2026 (no direct Homewyse page); cross-checked against Angi Chicago (loose handyman-minimum context)."},

  // ---------------- ELECTRICAL (common small items) ----------------
  {id:"electrical_outlet_replace",category:"Electrical",name:"Replace Electrical Outlet",unit:"each",laborRate:62,materialRate:15,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard receptacle swap, existing wiring.",source:"Homewyse.com national average reference, Sep 2026 ($276-334); cross-checked against iConduit Electric Chicago."},
  {id:"electrical_switch_replace",category:"Electrical",name:"Replace Light Switch",unit:"each",laborRate:55,materialRate:10,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard switch swap, existing wiring.",source:"Homewyse.com national average reference, Sep 2026 ($126-314); cross-checked against national Angi (no Chicago-specific plain-switch figure)."},
  {id:"electrical_fixture_replace",category:"Electrical",name:"Replace Light Fixture",unit:"each",laborRate:110,materialRate:65,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard fixture swap on existing electrical box.",source:"Homewyse.com national average reference, Sep 2026 ($394-583); cross-checked against Angi Chicago."}
];
