import type {CalcTask} from "./calcTypes";

/**
 * calcDefaults
 * ------------
 * The Calculator tab's editable labor/material pricing database — ported
 * from the standalone construction-estimator app's pricing-data.js.
 * Every rate is either a placeholder to edit for your own market, or a
 * rate calibrated against Homewyse.com's publicly displayed national
 * average figures (cited, with date, in each task's "source" field) —
 * never a copy of any proprietary per-ZIP calculator, branding, or
 * database.
 *
 * Users can edit every field from the Calculator tab's "Ціни калькулятора"
 * panel; edits are saved to this browser only (localStorage key
 * qc-calc-pricing-v1), same as the standalone app.
 */
export const calcDefaults:CalcTask[]=[

  // ---------------- FLOORING ----------------
  {id:"flooring_laminate_lvp_install",category:"Flooring",name:"Laminate / LVP Flooring Installation",unit:"sqft",laborRate:3.75,materialRate:3.50,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Includes standard underlayment and transitions. Does not include subfloor repair or self-leveling.",source:"Homewyse.com national average reference, May 2026 ($6.91–$11.81/sq ft installed)"},
  {id:"flooring_carpet_remove",category:"Flooring",name:"Carpet Removal & Disposal",unit:"sqft",laborRate:1.60,materialRate:0,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Includes carpet, pad, and tack strip removal and haul-away.",source:"Homewyse.com national average reference, May 2026 ($1.37–$2.49/sq ft)"},
  {id:"flooring_floor_prep_selfleveling",category:"Flooring",name:"Floor Prep / Self-Leveling Underlayment",unit:"sqft",laborRate:3.00,materialRate:1.70,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Standard localized leveling and adhesive removal. Does not include structural subfloor repair or major moisture remediation.",source:"Homewyse.com national average reference, May 2026 ($4.38–$5.27/sq ft underlayment)"},
  {id:"flooring_tile_floor_install",category:"Flooring",name:"Ceramic/Porcelain Floor Tile Installation",unit:"sqft",laborRate:7.10,materialRate:10.00,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standard-set tile, grout included. Waterproofing/membrane priced separately.",source:"Estimated placeholder — common trade rate; adjust to your tile supplier and labor cost."},
  {id:"flooring_lvp_remove",category:"Flooring",name:"Remove Old Laminate / LVP Flooring",unit:"sqft",laborRate:1.90,materialRate:0,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and haul-away of existing flooring.",source:"Estimated placeholder — adjust to your local disposal costs."},

  // ---------------- TRIM ----------------
  {id:"trim_baseboard_install",category:"Trim",name:"Baseboard Installation",unit:"linear_ft",laborRate:7.50,materialRate:2.80,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard MDF baseboard, caulked and nail holes filled, unpainted.",source:"Homewyse.com national average reference, May 2026 ($8.96–$13.71/linear ft)"},
  {id:"trim_shoe_molding_install",category:"Trim",name:"Shoe Molding Installation",unit:"linear_ft",laborRate:3.00,materialRate:0.90,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Installed alongside new flooring, caulked, unpainted.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"trim_door_casing_install",category:"Trim",name:"Door Casing Installation",unit:"linear_ft",laborRate:5.50,materialRate:1.80,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard door trim, one side.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"trim_baseboard_remove",category:"Trim",name:"Remove Existing Baseboard",unit:"linear_ft",laborRate:2.00,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and disposal of existing baseboard.",source:"Estimated placeholder."},
  {id:"trim_caulk_finish",category:"Trim",name:"Caulking & Finish Work",unit:"linear_ft",laborRate:1.50,materialRate:0.25,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.15},lowMult:0.85,highMult:1.25,notes:"Caulking baseboard, casing, and trim seams; filling nail holes.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- DRYWALL ----------------
  {id:"drywall_install",category:"Drywall",name:"Drywall Installation (hang, tape, mud, sand)",unit:"sqft",laborRate:1.90,materialRate:0.60,suppliesPct:0.08,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"New drywall hung, taped, mudded, and sanded — ready to prime and paint.",source:"Homewyse.com national average reference, May 2026 ($2.26–$2.69/sq ft)"},
  {id:"drywall_repair",category:"Drywall",name:"Drywall Repair (patch, hole, or small area)",unit:"each",laborRate:300,materialRate:35,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.25,notes:"One patch or hole, mudded, sanded, ready to paint. Priced per repair, not per square foot.",source:"Homewyse.com national average reference, May 2026 ($297–$472 per repair)"},
  {id:"drywall_insulation_wall",category:"Drywall",name:"Wall Insulation Installation",unit:"sqft",laborRate:1.20,materialRate:1.10,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard batt insulation in open wall cavities, before drywall.",source:"Homewyse.com national average reference, May 2026 ($1.87–$3.03/sq ft)"},
  {id:"drywall_new_wall_frame",category:"Drywall",name:"New Stud Wall Framing",unit:"linear_ft",laborRate:12.00,materialRate:4.50,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Wood or metal stud partition wall framing, priced per linear foot of wall.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- PAINTING ----------------
  {id:"paint_room_floor_sqft",category:"Painting",name:"Interior Room Painting (walls & trim, per sq ft of floor area)",unit:"sqft",laborRate:5.00,materialRate:1.30,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Two coats, walls and trim, lightly-textured surfaces. Quantity = room FLOOR area, not wall area (matches how most painters quote a whole room).",source:"Homewyse.com national average reference, May 2026 ($4.22–$8.19/sq ft of floor area)"},
  {id:"paint_wall_sqft",category:"Painting",name:"Paint Wall (per sq ft of wall surface)",unit:"sqft",laborRate:2.00,materialRate:0.50,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats, priced per sq ft of actual wall surface — use this instead of the per-floor-sqft room rate when you're only painting specific walls.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"paint_ceiling_sqft",category:"Painting",name:"Paint Ceiling",unit:"sqft",laborRate:2.10,materialRate:0.45,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"One coat ceiling paint, standard height.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"paint_trim_linear_ft",category:"Painting",name:"Paint Baseboards & Trim",unit:"linear_ft",laborRate:2.30,materialRate:0.30,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats on baseboard and door/window trim.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"paint_door_each",category:"Painting",name:"Paint Door (both sides)",unit:"each",laborRate:130,materialRate:20,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats, both faces, hardware masked or removed.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- DOORS ----------------
  {id:"door_install_interior",category:"Doors",name:"Install Interior Door (prehung)",unit:"each",laborRate:350,materialRate:180,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard prehung interior door with hardware.",source:"Homewyse.com national average reference, May 2026 ($444–$675 per door)"},
  {id:"door_remove_interior",category:"Doors",name:"Remove Interior Door",unit:"each",laborRate:90,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:90,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and disposal of existing door and frame if needed.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- BATHROOM ----------------
  {id:"bath_vanity_install",category:"Bathroom",name:"Install Bathroom Vanity",unit:"each",laborRate:280,materialRate:70,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Set and secure vanity cabinet; plumbing connection priced separately.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"bath_toilet_replace",category:"Bathroom",name:"Remove & Install Toilet",unit:"each",laborRate:160,materialRate:220,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard two-piece toilet, wax ring and supply line included.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"bath_faucet_replace",category:"Bathroom",name:"Replace Bathroom Faucet",unit:"each",laborRate:150,materialRate:90,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Standard single-hole faucet swap.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"bath_tile_wall_install",category:"Bathroom",name:"Install Wall Tile (shower/tub surround)",unit:"sqft",laborRate:9.00,materialRate:11.00,suppliesPct:0.06,suppliesFixed:0,minPrice:500,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Standard-set wall tile with waterproofing membrane priced separately.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- KITCHEN ----------------
  {id:"kitchen_cabinet_install",category:"Kitchen",name:"Install Kitchen Cabinet (per unit)",unit:"each",laborRate:130,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:130,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Labor to set and secure one pre-built cabinet box. Cabinet cost priced separately as material.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"kitchen_countertop_install",category:"Kitchen",name:"Install Countertop",unit:"linear_ft",laborRate:25,materialRate:45,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standard laminate/butcher-block countertop, priced per linear foot. Stone/quartz will run considerably higher — adjust materialRate.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"kitchen_faucet_replace",category:"Kitchen",name:"Replace Kitchen Faucet",unit:"each",laborRate:165,materialRate:120,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Standard single-hole kitchen faucet swap.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- DEMOLITION & CLEANUP ----------------
  {id:"demo_general_sqft",category:"Demolition",name:"General Interior Demolition",unit:"sqft",laborRate:2.20,materialRate:0,suppliesPct:0.10,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Non-structural demolition of finishes (drywall, trim, flooring).",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"demo_debris_haul_each",category:"Demolition",name:"Debris Haul-Away",unit:"each",laborRate:0,materialRate:0,suppliesPct:0,suppliesFixed:300,minPrice:300,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.3},lowMult:0.9,highMult:1.35,notes:"Loading and hauling construction debris to disposal. Scales with dumpster/truckloads needed — add more than one unit for larger jobs.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"demo_final_cleanup_room",category:"Demolition",name:"Final Job-Site Cleanup",unit:"room",laborRate:100,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.2},lowMult:0.9,highMult:1.2,notes:"Broom-clean and wipe-down at project completion.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"demo_protect_room",category:"Demolition",name:"Protect Floors & Furniture",unit:"room",laborRate:125,materialRate:0,suppliesPct:0.10,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.1},lowMult:0.9,highMult:1.2,notes:"Floor protection film/paper and furniture covering for the duration of the job.",source:"Estimated placeholder — common trade rate; adjust to your market."},

  // ---------------- ELECTRICAL (common small items) ----------------
  {id:"electrical_outlet_replace",category:"Electrical",name:"Replace Electrical Outlet",unit:"each",laborRate:55,materialRate:12,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard receptacle swap, existing wiring.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"electrical_switch_replace",category:"Electrical",name:"Replace Light Switch",unit:"each",laborRate:55,materialRate:10,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard switch swap, existing wiring.",source:"Estimated placeholder — common trade rate; adjust to your market."},
  {id:"electrical_fixture_replace",category:"Electrical",name:"Replace Light Fixture",unit:"each",laborRate:120,materialRate:55,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard fixture swap on existing electrical box.",source:"Estimated placeholder — common trade rate; adjust to your market."}
];
