import type {CalcTask} from "./calcTypes";

/**
 * calcDefaults
 * ------------
 * The Calculator tab's editable labor/material pricing database — ported
 * from the standalone construction-estimator app's pricing-data.js.
 * Every rate is either a placeholder to edit for your own market, or a
 * rate calibrated against Homewyse.com's publicly displayed national
 * average figures (cited, with date, in each task's "source" field) —
 * never a copy of any proprietary per-ZIP calculator, branding, or
 * database.
 *
 * Users can edit every field from the Calculator tab's "Ціни калькулятора"
 * panel; edits are saved to this browser only (localStorage key
 * qc-calc-pricing-v1), same as the standalone app.
 */
export const calcDefaults:CalcTask[]=[

  // ---------------- FLOORING ----------------
  {id:"flooring_laminate_lvp_install",category:"Flooring",name:"Laminate / LVP Flooring Installation",unit:"sqft",laborRate:3.75,materialRate:3.50,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Includes standard underlayment and transitions. Does not include subfloor repair or self-leveling.",source:"Homewyse.com national average reference, May 2026 ($6.91–$11.81/sq ft installed)"},
  {id:"flooring_carpet_remove",category:"Flooring",name:"Carpet Removal & Disposal",unit:"sqft",laborRate:1.60,materialRate:0,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Includes carpet, pad, and tack strip removal and haul-away.",source:"Homewyse.com national average reference, May 2026 ($1.37–$2.49/sq ft)"},
  {id:"flooring_floor_prep_selfleveling",category:"Flooring",name:"Floor Prep / Self-Leveling Underlayment",unit:"sqft",laborRate:3.00,materialRate:1.70,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Standard localized leveling and adhesive removal. Does not include structural subfloor repair or major moisture remediation.",source:"Homewyse.com national average reference, May 2026 ($4.38–$5.27/sq ft underlayment)"},
  {id:"flooring_lvp_remove",category:"Flooring",name:"Remove Old Laminate / LVP Flooring",unit:"sqft",laborRate:1.75,materialRate:0.25,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and haul-away of existing flooring.",source:"Homewyse.com national average reference, Sep 2026 ($2.42-4.47/sq ft (general flooring removal)); cross-checked against Angi / Budget Construction Chicago."},
  {id:"subfloor_prep_sqft",category:"Flooring",name:"Concrete Subfloor Cleaning & Prep",unit:"sqft",laborRate:1.15,materialRate:0.10,suppliesPct:0.10,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Scrape residual mastic/adhesive, vacuum and degrease a concrete slab; assumes non-asbestos mastic and a cleared room. Excludes grinding or shot-blasting.",source:"Homewyse.com national average reference, Sep 2026 ($0.37-0.70/sq ft clean concrete floor, $2.42-4.47/sq ft remove flooring); cross-checked against Angi Chicago flooring guide ($2-6/sq ft old-flooring removal)."},
  {id:"localized_floor_leveling_each",category:"Flooring",name:"Localized Floor Patching & Self-Leveling",unit:"each",laborRate:560,materialRate:190,suppliesPct:0.08,suppliesFixed:0,minPrice:500,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Flat per-area price for a few low/high spots in one room (~40-60 sq ft of feathering plus primer) -- not a whole-floor pour.",source:"Homewyse.com national average reference, Sep 2026 ($14.00-16.65/sq ft concrete repair, ~$560-1,000 per job); cross-checked against Homeyou Chicago concrete leveling ($500-1,500 per slab)."},
  {id:"floor_leveling_sqft",category:"Flooring",name:"Level Floor with Self-Leveling Compound",unit:"sqft",laborRate:2.85,materialRate:1.90,suppliesPct:0.08,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Full-room self-leveling underlayment at ~1/4 in average depth, including primer, perimeter dam and mixing. Deeper pours bill higher.",source:"Homewyse.com national average reference, Sep 2026 ($4.38-5.27/sq ft underlayment install, $1-5/sq ft compound); cross-checked against Angi Chicago flooring guide ($3-8/sq ft labor)."},
  {id:"underlayment_install_sqft",category:"Flooring",name:"Install Flooring Underlayment (foam/cork pad)",unit:"sqft",laborRate:0.60,materialRate:0.60,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Roll-out foam or cork pad under laminate/LVP including seam tape and trimming; assumes a prepped, level substrate.",source:"Homewyse.com national average reference, Sep 2026 ($4.38-5.27/sq ft structural underlayment; foam/cork pad far lower); cross-checked against Angi Chicago flooring guide ($0.50-5.00/sq ft underlayment)."},
  {id:"floor_transition_each",category:"Flooring",name:"Install Floor Transition Strip",unit:"each",laborRate:65,materialRate:25,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"One transition/threshold strip per doorway -- measure, cut, track or adhesive set, fasten. Mid-grade aluminum or wood T-mold; stone saddles bill higher.",source:"Homewyse.com national average reference, Sep 2026 ($283-366 per transition with 2-hr minimum; Porch $79-121 per strip); cross-checked against HomeGuide Chicago handyman rates ($40-75/hr)."},
  {id:"move_furniture_floor_room",category:"Flooring",name:"Move Furniture for Flooring Work",unit:"room",laborRate:110,materialRate:8,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Clear one average room and return the furniture after install, including blankets and floor film. Excludes appliances, safes and pianos.",source:"Homewyse.com national average reference, Sep 2026 (no dedicated furniture-moving guide; $50-100 per installer-hour industry standard); cross-checked against Angi Chicago flooring guide (furniture relocation $60-150/hr)."},

  // ---------------- TILE ----------------
  {id:"flooring_tile_floor_install",category:"Tile",name:"Ceramic/Porcelain Floor Tile Installation",unit:"sqft",laborRate:7.5,materialRate:9.0,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standard-set tile, grout included. Waterproofing/membrane priced separately.",source:"Homewyse.com national average reference, Sep 2026 ($16.38-20.21/sq ft); cross-checked against Budget Construction Co. / Homeyou Chicago."},
  {id:"bath_tile_wall_install",category:"Tile",name:"Install Wall Tile (shower/tub surround)",unit:"sqft",laborRate:9.5,materialRate:10.5,suppliesPct:0.06,suppliesFixed:0,minPrice:500,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Standard-set wall tile with waterproofing membrane priced separately.",source:"Homewyse.com national average reference, Sep 2026 ($11.48-21.27/sq ft); cross-checked against Angi / DoItOrHire Chicago."},
  {id:"tile_remove_sqft",category:"Tile",name:"Remove Old Tile",unit:"sqft",laborRate:4.50,materialRate:0.50,suppliesPct:0.10,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Demo ceramic/porcelain floor or wall tile down to substrate including haul-away. Use the difficult multiplier for thinset-bonded or mud-bed tile.",source:"Homewyse.com national average reference, Sep 2026 ($3.05-5.64/sq ft); cross-checked against Homeyou Chicago ($3-6/sq ft, $383-1,029 labor per 215 sq ft)."},
  {id:"uncoupling_membrane_sqft",category:"Tile",name:"Install Uncoupling Membrane (Ditra)",unit:"sqft",laborRate:2.75,materialRate:2.40,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Schluter Ditra or equivalent set in thinset over a prepped substrate; material is ~$2.13/sq ft membrane plus thinset. Excludes floor leveling.",source:"Homewyse.com national average reference, Sep 2026 ($4.38-5.27/sq ft underlayment install); no Chicago-specific membrane figure published -- cross-checked against Contractor+ Chicago labor rate ($45-70/hr)."},
  {id:"tile_waterproofing_sqft",category:"Tile",name:"Waterproof Tile Area (Kerdi / RedGard)",unit:"sqft",laborRate:4.50,materialRate:2.00,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Sheet (Kerdi) or liquid (RedGard) membrane on shower walls and pan including seam bands and corners; vertical work runs slower than floor.",source:"Homewyse.com national average reference, Sep 2026 ($1,570-1,945/shower, ~$16-19/sq ft incl. pan liner); no Chicago-specific per-sq-ft figure published -- cross-checked against Homeyou Chicago tile labor ($8-11/sq ft installed)."},
  {id:"tile_grout_sqft",category:"Tile",name:"Grout / Regrout Tile",unit:"sqft",laborRate:4.00,materialRate:0.50,suppliesPct:0.08,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standalone grouting or regrout including grout-saw removal, clean, float and haze wipe. Cement grout; use the difficult multiplier for epoxy.",source:"Homewyse.com national average reference, Sep 2026 ($15.84-34.75/sq ft full regrout); no Chicago-specific regrout figure published -- cross-checked against HomeGuide regrout range ($5-11/sq ft) and Contractor+ Chicago labor ($45-70/hr)."},
  {id:"schluter_edge_linear_ft",category:"Tile",name:"Install Schluter Tile Edge Profile",unit:"linear_ft",laborRate:6.50,materialRate:3.00,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Jolly/Schiene metal profile bedded in thinset at tile terminations; material ~$2.45/linear ft plus cut and miter waste. Roughly 6-10 linear ft per hour.",source:"Homewyse.com national average reference, Sep 2026 (tile trim install $4-8/linear ft); no Chicago-specific Schluter figure published -- cross-checked against Contractor+ Chicago labor rate ($45-70/hr)."},
  {id:"tile_silicone_linear_ft",category:"Tile",name:"Silicone Tile Joints",unit:"linear_ft",laborRate:5.50,materialRate:1.25,suppliesPct:0.05,suppliesFixed:0,minPrice:125,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.15},lowMult:0.85,highMult:1.25,notes:"Color-matched sanded silicone tooled into change-of-plane joints (corners, tub/tile, curb); ~1.5-2 hrs for a typical 30 linear ft shower. Excludes old-grout demo.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($2.45-5.03/linear ft); cross-checked against TaskRabbit Chicago sealing and caulking (avg $54/hr)."},
  {id:"vanity_backsplash_sqft",category:"Tile",name:"Install Vanity Backsplash Tile",unit:"sqft",laborRate:20.00,materialRate:9.00,suppliesPct:0.055,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Small 4-10 sq ft backsplash behind a vanity; high cut-to-field ratio, outlet cuts and edge trim push labor to ~2x the flat-wall rate.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($28.31-49.78/sq ft tile backsplash); cross-checked against Homeyou Chicago ceramic tile installation ($8-12/sq ft)."},
  {id:"shower_niche_tile_each",category:"Tile",name:"Tile Shower Niche",unit:"each",laborRate:250,materialRate:60,suppliesPct:0.06,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Only ~2-3 sq ft of tile but 2.5-3.5 hrs: waterproof detailing, mitered or metal-trim edges, sloped sill. Niche already framed and waterproofed.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($19.81-32.61/sq ft mosaic tile, ~$300-350 per niche); cross-checked against Assembly Squad Chicago custom tiled niche ($300-500)."},
  {id:"shower_bench_tile_each",category:"Tile",name:"Tile Shower Bench",unit:"each",laborRate:340,materialRate:95,suppliesPct:0.06,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"~6-8 sq ft across top and faces, 4-5 hrs: pitched top, mitered or trimmed front edge, corner detail. Bench already built and waterproofed.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($23.78-30.51/sq ft bathtub tile, ~$450-500 per bench); cross-checked against Angi Chicago shower installer labor ($50-100/hr)."},
  {id:"kitchen_backsplash_sqft",category:"Tile",name:"Install Kitchen Backsplash Tile",unit:"sqft",laborRate:18,materialRate:3.50,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Typical 30-45 sq ft run with outlet cuts and edge detail; customer supplies the tile, material covers thinset, grout, sealer, spacers and blades.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($28.31-49.78/sq ft incl. tile); cross-checked against Homeyou Chicago ceramic tile (labor ~$66-82/hr)."},
  {id:"cement_board_install_sqft",category:"Tile",name:"Install Cement Board (tile substrate)",unit:"sqft",laborRate:4.25,materialRate:2.00,suppliesPct:0.08,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Durock or HardieBacker set in thinset, screwed on the required pattern, seams taped with alkali-resistant mesh and mudded. Contractor supplies the board, thinset, screws and tape.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($8.18-9.13/sq ft all-in backer board); cross-checked against Homeyou Chicago tile labor (~$63-78/hr)."},

  // ---------------- TRIM ----------------
  {id:"trim_baseboard_install",category:"Trim",name:"Baseboard Installation",unit:"linear_ft",laborRate:7.50,materialRate:2.80,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard MDF baseboard, caulked and nail holes filled, unpainted.",source:"Homewyse.com national average reference, May 2026 ($8.96–$13.71/linear ft)"},
  {id:"trim_shoe_molding_install",category:"Trim",name:"Shoe Molding Installation",unit:"linear_ft",laborRate:3.0,materialRate:1.0,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Installed alongside new flooring, caulked, unpainted.",source:"Homewyse.com national average reference, Sep 2026 ($7.58-11.60/linear ft (general molding proxy)); cross-checked against Contractor+ Chicago."},
  {id:"trim_door_casing_install",category:"Trim",name:"Door Casing Installation",unit:"linear_ft",laborRate:6.0,materialRate:2.0,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard door trim, one side.",source:"Homewyse.com national average reference, Sep 2026 ($7.92-12.14/linear ft); cross-checked against Contractor+ Chicago."},
  {id:"trim_baseboard_remove",category:"Trim",name:"Remove Existing Baseboard",unit:"linear_ft",laborRate:2.0,materialRate:0.0,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and disposal of existing baseboard.",source:"Homewyse.com national average reference, Sep 2026 ($1.11-2.25/linear ft); cross-checked against no Chicago source found."},
  {id:"trim_caulk_finish",category:"Trim",name:"Caulking & Finish Work",unit:"linear_ft",laborRate:1.75,materialRate:0.3,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.15},lowMult:0.85,highMult:1.25,notes:"Caulking baseboard, casing, and trim seams; filling nail holes.",source:"Homewyse.com national average reference, Sep 2026 ($2.45-5.03/linear ft (exterior caulk proxy)); cross-checked against no Chicago source found."},
  {id:"baseboard_shoe_package_each",category:"Trim",name:"Baseboard + Shoe Molding Package (per room)",unit:"each",laborRate:650,materialRate:190,suppliesPct:0.05,suppliesFixed:0,minPrice:600,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Flat per-room package assuming ~40 linear ft of perimeter -- raise the quantity for larger rooms. Mitered, nailed, caulked and holes filled, ready for paint; contractor supplies the trim, nails, filler and caulk.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($8.96-13.71/linear ft baseboard installed, shoe priced separately); cross-checked against Contractor+ Chicago ($10.65/linear ft quarter round)."},
  {id:"fill_nail_holes_room",category:"Trim",name:"Fill Nail Holes & Trim Touch-Up",unit:"room",laborRate:90,materialRate:12,suppliesPct:0.08,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Per-room prep before painting: fill nail holes, caulk gaps and sand trim smooth. Assumes trim in sound condition -- not a substitute for trim repair.",source:"Homewyse.com has no cost guide for nail-hole filling as a standalone item (its Repair Wall Holes page covers large drywall holes and does not apply); rate derived from Chicago painter prep labor, cross-checked against Angi Chicago interior painting."},

  // ---------------- DRYWALL ----------------
  {id:"drywall_install",category:"Drywall",name:"Drywall Installation (hang, tape, mud, sand)",unit:"sqft",laborRate:1.90,materialRate:0.60,suppliesPct:0.08,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"New drywall hung, taped, mudded, and sanded — ready to prime and paint.",source:"Homewyse.com national average reference, May 2026 ($2.26–$2.69/sq ft)"},
  {id:"drywall_repair",category:"Drywall",name:"Drywall Repair (patch, hole, or small area)",unit:"each",laborRate:300,materialRate:35,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.25,notes:"One patch or hole, mudded, sanded, ready to paint. Priced per repair, not per square foot.",source:"Homewyse.com national average reference, May 2026 ($297–$472 per repair)"},
  {id:"drywall_insulation_wall",category:"Insulation",name:"Wall Insulation Installation",unit:"sqft",laborRate:1.20,materialRate:1.10,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard batt insulation in open wall cavities, before drywall.",source:"Homewyse.com national average reference, May 2026 ($1.87–$3.03/sq ft)"},
  {id:"drywall_new_wall_frame",category:"Drywall",name:"New Stud Wall Framing",unit:"linear_ft",laborRate:13.0,materialRate:5.5,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Wood or metal stud partition wall framing, priced per linear foot of wall.",source:"Homewyse.com national average reference, Sep 2026 ($3.88-6.62/sq ft face (~$31-53/lf at 8ft)); cross-checked against Angi Chicago."},
  {id:"drywall_finish_sqft",category:"Drywall",name:"Drywall Finishing (tape, mud, sand only)",unit:"sqft",laborRate:1.57,materialRate:0.28,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Tape, mud (2-3 coats) and sand new or patched seams -- finishing step only, does not include hanging the board.",source:"Homewyse.com national average reference, Sep 2026 ($1.20-2.90/sq ft by finish level); cross-checked against Angi Chicago ($0.95-2.90/sq ft)."},
  {id:"drywall_remove_sqft",category:"Drywall",name:"Remove Damaged Drywall",unit:"sqft",laborRate:1.25,materialRate:0.22,suppliesPct:0.08,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Cut out and haul away damaged gypsum board; no new board or finish included.",source:"Homewyse.com national average reference, Sep 2026 ($1.04-1.89/sq ft); cross-checked against Angi Chicago ($0.50-2.90/sq ft panel/plaster removal)."},
  {id:"drywall_crack_linear_ft",category:"Drywall",name:"Repair Drywall Crack",unit:"linear_ft",laborRate:1.53,materialRate:0.27,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Rout crack, mesh tape, 2 coats compound, sand; small jobs may hit the minimum price floor.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per standalone crack repair); cross-checked against Angi Chicago ($305-905 per repair job, avg $604)."},
  {id:"drywall_tape_repair_each",category:"Drywall",name:"Repair Loose Drywall Tape Seam",unit:"each",laborRate:165,materialRate:25,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Cut out failed tape seam (~2-3 ft), re-tape, 2-3 coats compound, sand -- single spot repair.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per standalone repair call, scaled for tape-only scope); cross-checked against Homeyou.com Chicago ($284 avg per patch)."},
  {id:"drywall_corner_repair_each",category:"Drywall",name:"Repair Damaged Drywall Corner",unit:"each",laborRate:180,materialRate:30,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Remove damaged corner bead (~3-4 linear ft), install new bead, 2-3 coats compound, sand.",source:"Homewyse.com national average reference, Sep 2026 ($4.06-4.89/linear ft corner bead plus finishing labor); cross-checked against Angi Chicago (drywall specialist rate ~$90/hr)."},
  {id:"drywall_patch_addon_minor",category:"Drywall",name:"Minor Drywall Patch (Add-on)",unit:"each",laborRate:78,materialRate:17,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Small nail/anchor hole patch (under 3in), done as an add-on during an in-progress repaint job -- no separate trip charge.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 standalone repair call, reduced for add-on/no-trip-charge scope); cross-checked against Angi Chicago (small-hole fix $25-125 each)."},
  {id:"drywall_patch_addon_medium",category:"Drywall",name:"Medium Drywall Patch (Add-on)",unit:"each",laborRate:185,materialRate:27,suppliesPct:0.08,suppliesFixed:0,minPrice:125,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Medium hole (~1-4 sq ft) patch/tape/mud/sand added during a repaint visit -- no separate trip charge, ~2 hrs on-site.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per standalone patch); cross-checked against Homeyou Chicago ($284/patch: ~$260 labor + $24 materials), discounted ~25% for bundled add-on."},
  {id:"drywall_patch_addon_large",category:"Drywall",name:"Large Drywall Repair (Add-on)",unit:"each",laborRate:300,materialRate:65,suppliesPct:0.08,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.85,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.25,notes:"Larger damaged section (~5-10 sq ft) replaced as an add-on during painting -- ~3-3.5 hrs on-site plus extra mud/tape/scrap drywall.",source:"Homewyse.com national average reference, Sep 2026 ($297-472/patch base scaled to $300-650 for larger bundled sections); cross-checked against Angi Chicago ($1,040-1,560 for a standalone 20 sq ft repair) scaled down for a smaller bundled add-on."},
  {id:"drywall_repair_standalone",category:"Drywall",name:"Standalone Drywall Repair Visit",unit:"each",laborRate:335,materialRate:50,suppliesPct:0.08,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standalone small-patch service call including trip/minimum-labor charge (~3.5-4 hrs), separate from any painting job.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per patch); cross-checked against Angi Chicago ($604 avg per standalone project, most $305-905; handyperson $60/hr, specialist $90/hr)."},
  {id:"insulation_drywall_package_each",category:"Insulation",name:"Insulation + Drywall Installation Package",unit:"each",laborRate:840,materialRate:560,suppliesPct:0.10,suppliesFixed:0,minPrice:800,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Bundled job for a typical ~300 sq ft of wall area: install open-cavity batt insulation, then hang/tape/mud/sand new drywall over it, per room/area.",source:"Homewyse.com national average reference, Sep 2026 ($3.93-5.45/sq ft combined, ~$1,180-1,635 for 300 sq ft); cross-checked against Angi Chicago ($1-4/sq ft insulation, whole-home avg $1,701, plus up to $600 for post-insulation drywall repair)."},

  // ---------------- PAINTING ----------------
  {id:"paint_room_floor_sqft",category:"Painting",name:"Interior Room Painting (walls & trim, per sq ft of floor area)",unit:"sqft",laborRate:5.00,materialRate:1.30,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Two coats, walls and trim, lightly-textured surfaces. Quantity = room FLOOR area, not wall area (matches how most painters quote a whole room).",source:"Homewyse.com national average reference, May 2026 ($4.22–$8.19/sq ft of floor area)"},
  {id:"paint_wall_sqft",category:"Painting",name:"Paint Wall (per sq ft of wall surface)",unit:"sqft",laborRate:1.9,materialRate:0.4,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats, priced per sq ft of actual wall surface — use this instead of the per-floor-sqft room rate when you're only painting specific walls.",source:"Homewyse.com national average reference, Sep 2026 ($1.29-2.78/sq ft); cross-checked against Angi Chicago."},
  {id:"paint_ceiling_sqft",category:"Painting",name:"Paint Ceiling",unit:"sqft",laborRate:2.0,materialRate:0.4,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"One coat ceiling paint, standard height.",source:"Homewyse.com national average reference, Sep 2026 ($1.37-2.95/sq ft); cross-checked against Angi Chicago."},
  {id:"paint_trim_linear_ft",category:"Painting",name:"Paint Baseboards & Trim",unit:"linear_ft",laborRate:2.15,materialRate:0.35,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats on baseboard and door/window trim.",source:"Homewyse.com national average reference, Sep 2026 ($1.60-3.39/linear ft (Paint Trim Molding)); cross-checked against Angi Chicago."},
  {id:"paint_door_each",category:"Painting",name:"Paint Door (both sides)",unit:"each",laborRate:160,materialRate:30,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Two coats, both faces, hardware masked or removed.",source:"Homewyse.com national average reference, Sep 2026 ($163-332/door); cross-checked against Contractor+ Chicago."},
  {id:"water_stain_block_each",category:"Painting",name:"Seal Water Stain (Stain-Blocking Primer)",unit:"each",laborRate:75,materialRate:18,suppliesPct:0.05,suppliesFixed:0,minPrice:60,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Spot-prime a small water-stain area (~4-9 sq ft) with stain-blocking primer before repainting -- minor add-on to a paint job.",source:"Homewyse.com national average reference, Sep 2026 (closest match 'Cost to Paint Wall', $1.29-2.78/sq ft, primer as job-supply line); cross-checked against Angi Chicago interior-painting guide (prep/patch $0.50-0.75/sq ft, primer ~$10/quart per 100 sq ft)."},
  {id:"paint_repaired_areas_each",category:"Painting",name:"Prime and Paint Repaired Areas",unit:"each",laborRate:310,materialRate:70,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes a patch up to ~4 sq ft: spot-prime plus 2 coats blended into the surrounding wall after a drywall repair -- per patch, not a full wall.",source:"Homewyse.com national average reference, Sep 2026 ($297-472 per patch); cross-checked against Homeyou Chicago."},
  {id:"paint_baseboard_shoe_package_each",category:"Painting",name:"Paint Baseboards & Shoe Molding Package",unit:"each",laborRate:160,materialRate:40,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes ~40 linear ft typical room perimeter; baseboards plus shoe molding together, prep/caulk and 2 coats.",source:"Homewyse.com national average reference, Sep 2026 ($2.30-4.88/linear ft baseboard basis); cross-checked against Homeyou Chicago ($2-4/linear ft trim)."},
  {id:"paint_door_frame_each",category:"Painting",name:"Paint Door Frame",unit:"each",laborRate:65,materialRate:15,suppliesPct:0.05,suppliesFixed:0,minPrice:60,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes ~17 linear ft of frame/casing per standard interior door opening, 2 coats -- not the door slab itself.",source:"Homewyse.com national average reference, Sep 2026 ($2.37-5.02/linear ft, ~$40-85/frame); cross-checked against Angi Chicago painting labor rates ($50-75/hr)."},
  {id:"paint_baseboards_linear_ft",category:"Painting",name:"Paint Baseboards (Only)",unit:"linear_ft",laborRate:2.60,materialRate:0.65,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Baseboards only, no shoe molding; standard prep, 2 coats.",source:"Homewyse.com national average reference, Sep 2026 ($2.30-4.88/linear ft); cross-checked against Homeyou Chicago ($2-4/linear ft)."},
  {id:"paint_window_each",category:"Painting",name:"Paint Window",unit:"each",laborRate:95,materialRate:20,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Assumes ~20 linear ft of sash/frame/trim per standard window, masking of glass, 2 coats.",source:"Homewyse.com national average reference, Sep 2026 ($3.72-7.69/linear ft, ~$75-155/window); cross-checked against Angi Chicago interior-painting labor rates ($50-75/hr)."},
  {id:"paint_wall_each",category:"Painting",name:"Paint One Wall",unit:"each",laborRate:168,materialRate:42,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Typical ~10x8 wall (80 sq ft), 2 coats, standard prep.",source:"Homewyse.com national average reference, Sep 2026 ($1.29-2.78/sq ft, ~$103-222/wall at 80 sq ft); cross-checked against Angi Chicago room-painting guide ($2.50-5/sq ft)."},
  {id:"paint_room",category:"Painting",name:"Paint Room Walls (Flat Rate)",unit:"room",laborRate:760,materialRate:190,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Typical bedroom ~129 sq ft of wall area (walls only), standard prep, 2 coats, no ceiling.",source:"Homewyse.com national average reference, Sep 2026 ($4.22-8.19/sq ft, ~$544-1057/room); cross-checked against Angi Chicago room-painting guide (avg $1,140, range $414-1,658)."},
  {id:"wallpaper_remove_sqft",category:"Painting",name:"Remove Wallpaper",unit:"sqft",laborRate:2.10,materialRate:0.25,suppliesPct:0.10,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:2.0},lowMult:0.85,highMult:1.3,notes:"Score, steam or soak, strip and wash down adhesive residue, leaving walls paint-ready. Rate assumes single-layer strippable paper -- old multi-layer, vinyl or painted-over paper takes far longer, so use the difficult multiplier.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($2.99-6.09/sq ft); cross-checked against Homeyou Chicago ($1-2/sq ft) and Contractor+ Chicago ($0.69/sq ft avg)."},

  // ---------------- DOORS ----------------
  {id:"door_install_interior",category:"Doors",name:"Install Interior Door (prehung)",unit:"each",laborRate:350,materialRate:180,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard prehung interior door with hardware.",source:"Homewyse.com national average reference, May 2026 ($444–$675 per door)"},
  {id:"door_remove_interior",category:"Doors",name:"Remove Interior Door",unit:"each",laborRate:90,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:90,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Removal and disposal of existing door and frame if needed.",source:"Homewyse.com national average reference, Sep 2026 ($19.43-33.25 (slab-only)); cross-checked against no Chicago source found."},

  // ---------------- BATHROOM ----------------
  {id:"bath_vanity_install",category:"Bathroom",name:"Install Bathroom Vanity",unit:"each",laborRate:280,materialRate:60,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.3,notes:"Set and secure vanity cabinet; plumbing connection priced separately.",source:"Homewyse.com national average reference, Sep 2026 ($576-871); cross-checked against Angi Chicago."},
  {id:"vanity_top_install_each",category:"Bathroom",name:"Install Vanity Top",unit:"each",laborRate:235,materialRate:35,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Set, level and seal a customer-supplied top on an existing cabinet (~2-3 hrs); material covers adhesive, shims, silicone and caulk only.",source:"Homewyse.com national average reference (checked Sep 2026) ($576-871 per job); cross-checked against Contractor+ Chicago."},
  {id:"vanity_remove_each",category:"Bathroom",name:"Remove Bathroom Vanity",unit:"each",laborRate:175,materialRate:45,suppliesPct:0.09,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Disconnect supply and drain, cut free, demo out and haul away, cap stubs; material is the dump fee plus floor protection and caps.",source:"Homewyse.com national average reference (checked Sep 2026) ($115-500 per job, $24.51-48.56/linear ft); cross-checked against Angi Chicago."},
  {id:"bathtub_remove_each",category:"Bathroom",name:"Remove Bathtub",unit:"each",laborRate:340,materialRate:60,suppliesPct:0.10,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.5},lowMult:0.85,highMult:1.3,notes:"Disconnect, break out and haul away a standard alcove tub; rate sits above national because Chicago bungalow and greystone stock is largely cast iron -- use the difficult multiplier for cast iron.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($134-260 per tub); cross-checked against Angi Chicago."},
  {id:"freestanding_tub_install_each",category:"Bathroom",name:"Install Freestanding Bathtub",unit:"each",laborRate:850,materialRate:150,suppliesPct:0.05,suppliesFixed:0,minPrice:750,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Set, level, secure and connect a customer-supplied tub to existing rough-in; material covers waste/overflow and drain kit, supply connectors, blocking, shims, leveling mortar and sealant. Tub not supplied.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($1,388-2,443 per tub incl. the tub); cross-checked against Angi Chicago."},
  {id:"shower_pan_build_each",category:"Bathroom",name:"Build & Waterproof Shower Pan",unit:"each",laborRate:620,materialRate:280,suppliesPct:0.05,suppliesFixed:0,minPrice:700,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Sloped mortar-bed or foam pan (~32x60) ready to tile; material covers deck mud, pre-slope, drain assembly, waterproofing membrane, cement board, fasteners and sealant. Tile priced separately.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($773-1,303 per shower base); cross-checked against Contractor+ Chicago."},
  {id:"shower_niche_build_each",category:"Bathroom",name:"Build Shower Niche (framing)",unit:"each",laborRate:350,materialRate:115,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Frame a recessed niche between studs with blocking and cement board or foam backer, ready for waterproofing and tile. Tiling the niche is a separate Tile task.",source:"No Homewyse cost guide exists for shower niches; cross-checked against Contractor+ Chicago ($403.66-807.32, avg $576.65 per niche)."},
  {id:"shower_bench_build_each",category:"Bathroom",name:"Build Shower Bench (framing)",unit:"each",laborRate:450,materialRate:175,suppliesPct:0.05,suppliesFixed:0,minPrice:450,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Frame a built-in bench and sheathe in cement board, ready for waterproofing and tile. Tiling the bench is a separate Tile task.",source:"No Homewyse cost guide exists for shower benches; HomeGuide national reference $250-1,000 installed -- no Chicago-specific published figure found."},
  {id:"shower_glass_panel_install_each",category:"Bathroom",name:"Install Fixed Shower Glass Panel",unit:"each",laborRate:325,materialRate:75,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Off-the-shelf fixed panel; material covers U-channel/clips, anchors, setting blocks and silicone only -- the panel itself is not supplied.",source:"Homewyse.com national average reference (checked Sep 2026) ($368-520 per job); cross-checked against Homeyou Chicago."},
  {id:"shower_glass_door_install_each",category:"Bathroom",name:"Install Stock Shower Glass Door",unit:"each",laborRate:475,materialRate:95,suppliesPct:0.05,suppliesFixed:0,minPrice:450,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Stock framed or semi-frameless door; material covers track, jambs, anchors, sweeps and sealant only -- the door unit is not supplied.",source:"Homewyse.com national average reference (checked Sep 2026) ($602-912 per door); cross-checked against Homeyou Chicago."},
  {id:"frameless_glass_enclosure_install_each",category:"Bathroom",name:"Custom Frameless Shower Enclosure (supplied & installed)",unit:"each",laborRate:850,materialRate:1150,suppliesPct:0.05,suppliesFixed:0,minPrice:1200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"The one item where material DOES include the product: fabricated 3/8in tempered glass plus hinges, clamps and header, since frameless is sold supplied-and-installed. Labor covers measure, template, trip and set.",source:"Homewyse.com national average reference (checked Sep 2026) ($888-1,297 per job); cross-checked against IMAGO Glass Inc. Chicago ($900-1,300 single door; multi-panel runs $2,000-4,000)."},
  {id:"bathroom_mirror_install_each",category:"Bathroom",name:"Install Bathroom Mirror",unit:"each",laborRate:85,materialRate:12,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Customer supplies the mirror; material covers cleats/J-channel, anchors, mirror-safe silicone and screws. Assumes a ready-made mirror under ~10 sq ft on drywall or studs -- tile or masonry adds time.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($13.86-19.93/sq ft, ~$104-150 for a 30x36in mirror incl. the glass); cross-checked against HomeBlue Chicago handyman rates ($50-100/hr)."},
  {id:"towel_warmer_install_each",category:"Bathroom",name:"Install Towel Warmer",unit:"each",laborRate:185,materialRate:20,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.3,notes:"Covers a plug-in unit, or a hardwired unit on an EXISTING GFCI circuit; a new dedicated circuit is a separate electrical item. Customer supplies the warmer; material covers anchors, blocking and connectors.",source:"Homewyse.com has no towel-warmer page (closest, Install Electric Wall Heater, includes the unit and a new circuit, so not comparable; CostHelper hardwired-install labor $100-250 used instead); cross-checked against 365Taskers Chicago handyman rates (typical $67/hr)."},
  {id:"towel_bar_install_each",category:"Bathroom",name:"Install Towel Bar",unit:"each",laborRate:55,materialRate:8,suppliesPct:0.05,suppliesFixed:0,minPrice:50,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.25,notes:"Customer supplies the bar; material covers anchors, screws and setscrews. Assumes drywall or stud mounting -- use the difficult multiplier when drilling tile.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($60.84-134 per bar, bar included); cross-checked against Homer Fixed It Chicago published pricing ($35-60 each)."},
  {id:"toilet_paper_holder_install_each",category:"Bathroom",name:"Install Toilet Paper Holder",unit:"each",laborRate:45,materialRate:6,suppliesPct:0.05,suppliesFixed:0,minPrice:45,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.25,notes:"Customer supplies the holder; material covers toggle anchors, screws and setscrew hardware. Typically 20-30 min -- bill alongside other accessories to clear the minimum.",source:"Homewyse.com has no toilet-paper-holder page (closest national reference, Install Hardware, $26.09-70.83 per item); cross-checked against Homer Fixed It Chicago published pricing ($35-60 each)."},
  {id:"robe_hook_install_each",category:"Bathroom",name:"Install Robe Hook",unit:"each",laborRate:40,materialRate:5,suppliesPct:0.05,suppliesFixed:0,minPrice:40,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.25,notes:"Customer supplies the hook; material covers anchors and screws. Smallest accessory task -- best sold bundled with others.",source:"Homewyse.com has no robe-hook page (closest national reference, Install Hardware, $26.09-70.83 per item); cross-checked against Homer Fixed It Chicago published pricing ($35-60 each)."},
  {id:"medicine_cabinet_install_each",category:"Bathroom",name:"Install Medicine Cabinet",unit:"each",laborRate:210,materialRate:30,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.5},lowMult:0.85,highMult:1.3,notes:"Customer supplies the cabinet; material covers anchors, blocking, screws and sealant. Surface-mount runs 1.5-2 hrs, recessed 3-4 hrs because of the wall opening and framing -- use the difficult multiplier for recessed.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($339-841 per cabinet incl. the cabinet; ~$190-390 net of the fixture); cross-checked against Homeyou Chicago handyman costs ($60-70/hr)."},
  {id:"bathroom_accessories_set_each",category:"Bathroom",name:"Install Bathroom Accessories Set",unit:"each",laborRate:200,materialRate:25,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Bundled four-piece set (towel bar, hook, paper holder, shelf) mounted on one visit, ~2.5-3 hrs -- cheaper than four separate trips. Customer supplies the accessories.",source:"Homewyse.com has no bundled-set guide; closest is the towel bar page (stamped May 2026, checked Sep 2026) ($60.84-134 per bar incl. the bar, so ~$243-536 for four); cross-checked against Homeyou Chicago handyman costs ($60-70/hr)."},

  // ---------------- PLUMBING ----------------
  {id:"bath_toilet_replace",category:"Plumbing",name:"Remove & Install Toilet",unit:"each",laborRate:160,materialRate:230,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Standard two-piece toilet, wax ring and supply line included.",source:"Homewyse.com national average reference, Sep 2026 ($707-1238); cross-checked against Angi Chicago."},
  {id:"bath_faucet_replace",category:"Plumbing",name:"Replace Bathroom Faucet",unit:"each",laborRate:150,materialRate:110,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Standard single-hole faucet swap.",source:"Homewyse.com national average reference, Sep 2026 ($511-717); cross-checked against Angi Chicago (kitchen proxy)."},
  {id:"kitchen_faucet_replace",category:"Plumbing",name:"Replace Kitchen Faucet",unit:"each",laborRate:165,materialRate:120,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Standard single-hole kitchen faucet swap.",source:"Homewyse.com national average reference, Sep 2026 ($539-861); cross-checked against Angi Chicago."},
  {id:"bathroom_sink_install_each",category:"Plumbing",name:"Install Bathroom Sink",unit:"each",laborRate:285,materialRate:45,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Set an undermount or drop-in sink in an existing top, seal, and connect drain and tailpiece (~2-2.5 hrs). Customer supplies the sink -- material covers putty, silicone, drain kit and clips.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($611-914 per sink, sink included); cross-checked against Plumbing Price Guide Chicago (journeyman $110-145/hr)."},
  {id:"vanity_plumbing_connect_each",category:"Plumbing",name:"Connect Vanity Plumbing",unit:"each",laborRate:215,materialRate:55,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Hook up hot/cold risers, P-trap and drain to an installed vanity and sink (~1.5-2 hrs); material covers the trap kit, braided supply lines, escutcheons, tape and putty.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($313-393 per sink trap assembly); cross-checked against Plumbing Price Guide Chicago (journeyman $110-145/hr)."},
  {id:"shower_valve_roughin_each",category:"Plumbing",name:"Replace Shower Valve Rough-In",unit:"each",laborRate:520,materialRate:95,suppliesPct:0.08,suppliesFixed:0,minPrice:450,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Open the wall, cut out the old valve, install and connect a new pressure-balance or thermostatic body, secure to blocking and pressure test. Valve supplied by customer; drywall patch and tile not included.",source:"Homewyse.com national average reference (checked Sep 2026) ($639-1,020 per shower faucet incl. fixture; $285-342 per valve repair); cross-checked against Plumbing Price Guide Chicago."},
  {id:"shower_trim_install_each",category:"Plumbing",name:"Install Shower Trim & Handle",unit:"each",laborRate:185,materialRate:25,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Mount the finish trim plate, cartridge, handle and escutcheon on an existing valve, set stop limits and leak-check. Trim kit supplied by customer.",source:"Homewyse.com national average reference (checked Sep 2026) ($639-1,020 per faucet install, fixture excluded); cross-checked against Angi Chicago plumber cost ($45-200/hr, $202-535 typical job)."},
  {id:"shower_head_install_each",category:"Plumbing",name:"Install / Replace Shower Head",unit:"each",laborRate:135,materialRate:15,suppliesPct:0.05,suppliesFixed:0,minPrice:125,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Swap a head on an existing shower arm -- under an hour, but carries a minimum charge. Head supplied by customer; material is tape, washers and silicone.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($175-451 per head, head included); no Chicago-specific shower-head figure published -- nearest local datapoint is Contractor+ Chicago ($70.87-141.73 all-in)."},
  {id:"handheld_shower_install_each",category:"Plumbing",name:"Install Handheld Shower",unit:"each",laborRate:210,materialRate:35,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.25,notes:"Anchor a slide bar or wall bracket into tile and connect hose and diverter (~1.5-2 hrs including tile drilling); kit supplied by customer, material covers tile-rated anchors, washers, tape and silicone.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($175-451 per shower head, head included); cross-checked against Contractor+ Chicago handheld head ($70.87-141.73 all-in)."},
  {id:"bathtub_faucet_install_each",category:"Plumbing",name:"Install Bathtub Faucet / Tub Filler",unit:"each",laborRate:340,materialRate:50,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Mount and connect the tub spout and filler trim to an existing rough-in valve (~2.5-3 hrs). Faucet/trim kit supplied by customer.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($692-1,060 per tub faucet, faucet included); cross-checked against Plumbing Price Guide Chicago (faucet installation $175-495, typical $285)."},
  {id:"shower_drain_install_each",category:"Plumbing",name:"Install Shower Drain",unit:"each",laborRate:265,materialRate:55,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Set the drain body in the pan or base and tie into the existing waste line with proper weep and slope, then test. Drain assembly supplied by customer.",source:"Homewyse.com national average reference (checked Sep 2026) ($412-497 per drain); cross-checked against Angi Chicago plumber cost."},
  {id:"shower_drain_relocate_each",category:"Plumbing",name:"Relocate Shower Drain",unit:"each",laborRate:560,materialRate:90,suppliesPct:0.09,suppliesFixed:0,minPrice:500,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.5},lowMult:0.85,highMult:1.3,notes:"Cut slab or joists, reroute and re-pitch the waste line to the new location, reconnect and test. Excludes concrete replacement, structural repair and the drain fixture.",source:"Homewyse.com national average reference (checked Sep 2026) ($909-1,106 per piping run); cross-checked against Angi Chicago pipe replacement ($451-2,728)."},
  {id:"water_lines_relocate_fixture",category:"Plumbing",name:"Relocate Water Supply Lines (one fixture)",unit:"each",laborRate:360,materialRate:70,suppliesPct:0.08,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Open the wall, cap and reroute hot/cold supply to the new fixture location, add stops and blocking, pressure test. Fixture not included; material is PEX or copper, fittings and hangers.",source:"Homewyse.com national average reference (checked Sep 2026) ($935-1,138 per piping run); cross-checked against Angi Chicago pipe replacement -- no Chicago-specific per-fixture reroute figure is published."},
  {id:"garbage_disposal_replace",category:"Plumbing",name:"Replace Garbage Disposal",unit:"each",laborRate:215,materialRate:30,suppliesPct:0.05,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Remove the old unit, mount the new one to the existing sink flange and reconnect discharge and power (~1.5-2 hrs). Install materials only -- add $120-250 if you supply a 1/2-3/4 HP unit.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($493-578 per disposal, unit included); cross-checked against VanDerBosch Plumbing Chicago (labor $100-200, all-in $280-578)."},
  {id:"kitchen_sink_install_each",category:"Plumbing",name:"Install Kitchen Sink",unit:"each",laborRate:420,materialRate:55,suppliesPct:0.05,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Set an undermount or drop-in sink, connect drain, strainer and disposal flange. Customer supplies the sink; material covers supply lines, trap kit, putty and silicone.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($472-569 per sink, labor plus supplies, sink excluded); cross-checked against Angi plumber rates ($50-200/hr) with Assembly Squad Chicago's published 15-25% Chicago premium."},

  // ---------------- KITCHEN ----------------
  {id:"kitchen_cabinet_install",category:"Kitchen",name:"Install Kitchen Cabinet (per unit)",unit:"each",laborRate:130,materialRate:0,suppliesPct:0.05,suppliesFixed:0,minPrice:130,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Labor to set and secure one pre-built cabinet box. Cabinet cost priced separately as material.",source:"Homewyse.com national average reference, Sep 2026 ($486-736 (bundled material)); cross-checked against Homeyou Chicago."},
  {id:"kitchen_countertop_install",category:"Kitchen",name:"Install Countertop",unit:"linear_ft",laborRate:25,materialRate:50,suppliesPct:0.05,suppliesFixed:0,minPrice:400,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Standard laminate/butcher-block countertop, priced per linear foot. Stone/quartz will run considerably higher — adjust materialRate.",source:"Homewyse.com national average reference, Sep 2026 ($41.94-63.77/sq ft (laminate)); cross-checked against SlabWise Chicago."},
  {id:"kitchen_cabinet_remove_each",category:"Kitchen",name:"Remove Kitchen Cabinet (per box)",unit:"each",laborRate:48,materialRate:12,suppliesPct:0.10,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.3,notes:"Unscrew, pry out and haul one cabinet box (~2 linear ft); material is the disposal share plus blades and bags. A full kitchen is typically 10-20 boxes -- set the quantity accordingly.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($28.73-59.48/linear ft, ~$57-119 per 2-ft box incl. disposal -- Homewyse prices this per linear foot, so the per-box rate is a derived conversion); cross-checked against Homeyou Chicago cabinet installation."},
  {id:"kitchen_hardware_install_each",category:"Kitchen",name:"Install Cabinet Hardware (per knob/pull)",unit:"each",laborRate:12,materialRate:1.50,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Per knob or pull, jig-drilled and mounted; batch rate for 20-40 pieces. Customer supplies the hardware; material covers jig wear, bits and longer screws.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($31.34-48.82 per handle, but that is a single-handle minimum including the handle); cross-checked against Homeyou Chicago handyman rate ($60-90/hr)."},
  {id:"dishwasher_install_each",category:"Kitchen",name:"Install Dishwasher",unit:"each",laborRate:260,materialRate:45,suppliesPct:0.05,suppliesFixed:0,minPrice:250,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.25,notes:"Slide in, level, connect supply, drain to disposal or air gap, and power. Customer supplies the appliance; material covers braided line, elbow, drain hose, clamps and air gap.",source:"Homewyse.com dishwasher page (stamped May 2026, checked Sep 2026) quotes $904-1,678, which appears to bundle the appliance, so it was not used directly; rate anchored on Angi and Thumbtack Chicago appliance-installer labor."},
  {id:"range_hood_install_each",category:"Kitchen",name:"Install Range Hood",unit:"each",laborRate:320,materialRate:45,suppliesPct:0.05,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Mount and connect to EXISTING duct and power; a new duct run adds roughly $400-700 -- use the difficult multiplier or add a separate line. Customer supplies the hood.",source:"Homewyse.com has no range-hood page; closest is Install Vent Hood (stamped May 2026, checked Sep 2026) ($564-1,030 per hood, appears to include a 350 CFM unit); cross-checked against Angi range-hood guide (labor $50-100/hr)."},

  // ---------------- DEMOLITION & CLEANUP ----------------
  {id:"demo_general_sqft",category:"Demolition",name:"General Interior Demolition",unit:"sqft",laborRate:2.0,materialRate:0.15,suppliesPct:0.10,suppliesFixed:0,minPrice:300,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Non-structural demolition of finishes (drywall, trim, flooring).",source:"Homewyse.com national average reference, Sep 2026 ($1.04-1.89/sq ft (wallboard removal proxy)); cross-checked against Homeyou Chicago."},
  {id:"demo_debris_haul_each",category:"Demolition",name:"Debris Haul-Away",unit:"each",laborRate:0,materialRate:0,suppliesPct:0,suppliesFixed:300,minPrice:300,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.3},lowMult:0.9,highMult:1.35,notes:"Loading and hauling construction debris to disposal. Scales with dumpster/truckloads needed — add more than one unit for larger jobs.",source:"Homewyse.com national average reference, Sep 2026 ($70.51-82.61/cu yd); cross-checked against GoLoadUp Chicago."},
  {id:"demo_final_cleanup_room",category:"Demolition",name:"Final Job-Site Cleanup",unit:"room",laborRate:110,materialRate:10,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.2},lowMult:0.9,highMult:1.2,notes:"Broom-clean and wipe-down at project completion.",source:"Homewyse.com national average reference, Sep 2026 ($119-153/room); cross-checked against Angi Chicago."},
  {id:"demo_protect_room",category:"Demolition",name:"Protect Floors & Furniture",unit:"room",laborRate:100,materialRate:25,suppliesPct:0.10,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:1.0,standard:1.0,difficult:1.1},lowMult:0.9,highMult:1.2,notes:"Floor protection film/paper and furniture covering for the duration of the job.",source:"Homewyse.com national average reference, Sep 2026 (no direct Homewyse page); cross-checked against Angi Chicago (loose handyman-minimum context)."},
  {id:"bathroom_debris_haul_each",category:"Demolition",name:"Haul Away Bathroom Debris",unit:"each",laborRate:150,materialRate:90,suppliesPct:0.10,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Single-bathroom gut, 2-3 cubic yards: labor is load-out, stair carry and drive; material is the C&D tipping fee. Lands below the general per-load haul task because this is a partial load -- a cast-iron tub or mortar-bed tile warrants the difficult multiplier.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($70.51-82.61/cu yd, so $141-248 for 2-3 yd); cross-checked against Angi Chicago junk removal (1/8 truckload $80-130)."},
  {id:"bathroom_final_cleanup_each",category:"Demolition",name:"Final Bathroom Cleanup",unit:"each",laborRate:125,materialRate:20,suppliesPct:0.05,suppliesFixed:0,minPrice:125,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.2,notes:"Dust, wipe-down, fixture and glass polish, protection removal -- roughly 2.5 hrs of detail cleaning.",source:"Homewyse.com national average reference (page stamped September 2026, checked Sep 2026) ($119-147 per room); cross-checked against Angi Chicago post-construction cleanup (~$50/hr, $150 job minimum)."},

  // ---------------- ELECTRICAL (common small items) ----------------
  {id:"electrical_outlet_replace",category:"Electrical",name:"Replace Electrical Outlet",unit:"each",laborRate:62,materialRate:15,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard receptacle swap, existing wiring.",source:"Homewyse.com national average reference, Sep 2026 ($276-334); cross-checked against iConduit Electric Chicago."},
  {id:"outlet_new_each",category:"Electrical",name:"Install New Electrical Outlet",unit:"each",laborRate:215,materialRate:55,suppliesPct:0.09,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.5},lowMult:0.85,highMult:1.3,notes:"New box plus a branch run from an existing circuit; drywall patch and paint excluded. NOTE: Chicago proper requires EMT conduit (no romex) and a licensed electrical contractor with a permit, so city jobs run above national -- suburban Cook and collar counties allow NM cable and price lower.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($297-360 per outlet); cross-checked against Angi Chicago."},
  {id:"gfci_install_each",category:"Electrical",name:"Install GFCI Outlet",unit:"each",laborRate:105,materialRate:28,suppliesPct:0.05,suppliesFixed:0,minPrice:100,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Swap an existing receptacle for a GFCI on an existing box, test and label downstream protection. No wall opening and no permit for a like-for-like swap.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($328-395 per outlet); cross-checked against iConduit Electric Chicago."},
  {id:"dimmer_install_each",category:"Electrical",name:"Install Dimmer Switch",unit:"each",laborRate:85,materialRate:32,suppliesPct:0.05,suppliesFixed:0,minPrice:90,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Replace an existing switch with a dimmer on an existing box; confirm neutral and load compatibility. Material assumes a standard LED-rated dimmer -- smart or Lutron-grade dimmers are customer-supplied.",source:"Homewyse.com has no dimmer-swap page; closest is Install Light Switch (stamped May 2026, checked Sep 2026) ($255-309 per switch); cross-checked against iConduit Electric Chicago."},
  {id:"recessed_light_install_each",category:"Electrical",name:"Install Recessed Light",unit:"each",laborRate:135,materialRate:38,suppliesPct:0.08,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.5},lowMult:0.85,highMult:1.3,notes:"Cut one can or canless LED into an existing ceiling and tie to an existing circuit. Assumes attic or open joist-bay access -- plaster ceilings, insulation or blocked bays need the difficult multiplier. Customer supplies the fixture.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($380-529 per light); cross-checked against iConduit Electric Chicago."},
  {id:"electrical_box_relocate_each",category:"Electrical",name:"Relocate Electrical Box",unit:"each",laborRate:175,materialRate:40,suppliesPct:0.09,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Move one box on the same wall: open the wall, extend or reroute the run, set a new old-work box, blank the old opening and reinstall the device. Patch and paint excluded.",source:"Homewyse.com national average reference (Relocate Electric Switch, page stamped September 2026, checked Sep 2026) ($258-312 per switch); cross-checked against iConduit Electric Chicago hourly rates."},
  {id:"new_circuit_each",category:"Electrical",name:"Add New Dedicated Circuit",unit:"each",laborRate:560,materialRate:135,suppliesPct:0.09,suppliesFixed:0,minPrice:550,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.5},lowMult:0.85,highMult:1.3,notes:"Homerun from the panel to one device: new breaker, full circuit run, terminate at a single outlet or appliance connection; patch excluded. Chicago requires a licensed contractor, permit and inspection. Assumes an open breaker slot -- a panel upgrade is separate.",source:"Homewyse.com national average reference (Install Appliance Circuit, page stamped May 2026, checked Sep 2026) ($741-910 per circuit); cross-checked against Angi Chicago dedicated-circuit data."},
  {id:"vanity_light_install_each",category:"Electrical",name:"Install Vanity Light",unit:"each",laborRate:135,materialRate:15,suppliesPct:0.05,suppliesFixed:0,minPrice:125,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Mount a vanity light above the mirror on existing wiring and box. Customer supplies the fixture; material covers the mounting strap, wire nuts, connectors and caulk.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($230-583 per fixture incl. the fixture at $91-216); cross-checked against Angi Chicago light fixture installation (labor $55-260)."},
  {id:"bath_fan_install_each",category:"Electrical",name:"Install Bathroom Exhaust Fan (new)",unit:"each",laborRate:340,materialRate:65,suppliesPct:0.10,suppliesFixed:0,minPrice:350,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.4},lowMult:0.85,highMult:1.3,notes:"Where no fan existed: cut-in, blocking, a new duct run to the exterior, wall or roof cap, and wiring to the switch. Customer supplies the fan; material covers duct, clamps, exterior cap, blocking and caulk.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($343-889 per fan incl. the fan); cross-checked against Angi Chicago bathroom fan installation ($217-581, avg $398)."},
  {id:"bath_fan_replace",category:"Electrical",name:"Replace Bathroom Exhaust Fan",unit:"each",laborRate:195,materialRate:25,suppliesPct:0.08,suppliesFixed:0,minPrice:200,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.25,notes:"Existing duct and wiring reused -- housing swap or retrofit unit. Customer supplies the fan; material covers the duct collar, wire nuts, connector and caulk.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($191-411 per fan incl. the fan); cross-checked against 5 Talents Renovations Thumbtack Chicago ($300 bath fan replacement)."},
  {id:"ceiling_fan_replace",category:"Electrical",name:"Replace Ceiling Fan",unit:"each",laborRate:215,materialRate:20,suppliesPct:0.05,suppliesFixed:0,minPrice:175,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.35},lowMult:0.85,highMult:1.25,notes:"Existing fan-rated box reused. Customer supplies the fan; material covers wire nuts, canopy and downrod hardware. If the box is not fan-rated, price the box replacement separately.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($669-1,118 per fan, but that includes the fan and a new box, so it is high for a like-for-like swap); cross-checked against Angi Chicago ceiling fan installation ($146-363, avg $253)."},
  {id:"light_fixture_remove_each",category:"Electrical",name:"Remove Light Fixture",unit:"each",laborRate:65,materialRate:8,suppliesPct:0.05,suppliesFixed:0,minPrice:60,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.2},lowMult:0.85,highMult:1.25,notes:"Power off, fixture down, conductors capped and the box covered, leaving it safe before painting or demolition. Material covers wire nuts, a blank cover plate, tape and labeling.",source:"Homewyse.com national average reference (page stamped May 2026, checked Sep 2026) ($21-75 per fixture, assumes batch work with no trip minimum); cross-checked against Angi Chicago handyman prices."},
  {id:"light_fixture_reinstall_each",category:"Electrical",name:"Reinstall Light Fixture",unit:"each",laborRate:95,materialRate:10,suppliesPct:0.05,suppliesFixed:0,minPrice:90,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.25},lowMult:0.85,highMult:1.25,notes:"Rehang a previously removed fixture on the same box after paint or repair, including re-terminating and testing.",source:"Homewyse.com has no fixture-reinstall page; nearest is the lighting fixture install guide (stamped May 2026, checked Sep 2026) ($230-583 incl. the fixture); cross-checked against Angi Chicago handyman light fixture installation ($105-415)."},
  {id:"electrical_switch_replace",category:"Electrical",name:"Replace Light Switch",unit:"each",laborRate:55,materialRate:10,suppliesPct:0.05,suppliesFixed:0,minPrice:75,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard switch swap, existing wiring.",source:"Homewyse.com national average reference, Sep 2026 ($126-314); cross-checked against national Angi (no Chicago-specific plain-switch figure)."},
  {id:"electrical_fixture_replace",category:"Electrical",name:"Replace Light Fixture",unit:"each",laborRate:110,materialRate:65,suppliesPct:0.05,suppliesFixed:0,minPrice:150,difficultyMultipliers:{basic:0.9,standard:1.0,difficult:1.3},lowMult:0.85,highMult:1.25,notes:"Standard fixture swap on existing electrical box.",source:"Homewyse.com national average reference, Sep 2026 ($394-583); cross-checked against Angi Chicago."}
];
