import type {PriceRule} from "./types";

import {materialDefaults} from "./materialDefaults";
import {approvedRule} from "./approvedRates";
const legacy:PriceRule[]=[
{id:"vanity_top_install_each",name:"Install vanity top",aliases:["install vanity top","vanity countertop installation","встановити стільницю vanity","монтаж стільниці у ванній"],unit:"each",rate:250},
{id:"bathroom_sink_install_each",name:"Install bathroom sink",aliases:["install bathroom sink","install vanity sink","bathroom sink installation","встановити умивальник","встановити sink у vanity"],unit:"each",rate:225},
{id:"vanity_backsplash_sqft",name:"Install vanity backsplash",aliases:["install vanity backsplash","bathroom backsplash","tile backsplash behind vanity","встановити backsplash біля vanity","плитка над тумбою"],unit:"sqft",rate:18},
{id:"vanity_remove_each",name:"Remove bathroom vanity",aliases:["remove bathroom vanity","vanity demolition","демонтувати vanity","зняти тумбу у ванній"],unit:"each",rate:250},
{id:"bathroom_debris_haul_each",name:"Haul away bathroom debris",aliases:["haul away bathroom debris","remove bathroom debris","construction debris removal","вивезти сміття з ванної","вивіз будівельного сміття"],unit:"each",rate:300},
{id:"bathroom_final_cleanup_each",name:"Final bathroom cleanup",aliases:["final bathroom cleanup","clean bathroom after renovation","фінальне прибирання ванної","прибрати ванну після ремонту"],unit:"each",rate:150},
{id:"shower_glass_panel_install_each",name:"Install fixed shower glass panel",aliases:["install fixed shower glass panel","install shower glass panel","fixed glass panel","встановити нерухому скляну панель","встановити скло в душі"],unit:"each",rate:450},
{id:"shower_glass_door_install_each",name:"Install shower glass door",aliases:["install shower glass door","install glass shower door","shower door installation","встановити скляні двері в душ","монтаж shower door"],unit:"each",rate:650},
{id:"frameless_glass_enclosure_install_each",name:"Install custom frameless shower enclosure",aliases:["install frameless shower enclosure","custom shower glass enclosure","frameless glass installation","встановити безрамне скло в душі","монтаж custom shower glass"],unit:"each",rate:1200},
{id:"shower_niche_build_each",name:"Build shower niche",aliases:["build shower niche","frame shower niche","construct shower niche","зробити нішу в душі","сформувати нішу"],unit:"each",rate:450},
{id:"shower_niche_tile_each",name:"Tile shower niche",aliases:["tile shower niche","install tile in niche","обкласти нішу плиткою","плитка в душовій ніші"],unit:"each",rate:250},
{id:"shower_bench_build_each",name:"Build shower bench",aliases:["build shower bench","construct shower bench","frame shower bench","зробити лавку в душі","побудувати shower bench"],unit:"each",rate:650},
{id:"shower_bench_tile_each",name:"Tile shower bench",aliases:["tile shower bench","install tile on shower bench","обкласти лавку плиткою","плитка на shower bench"],unit:"each",rate:350},
{id:"bathroom_mirror_install_each",name:"Install bathroom mirror",aliases:["install bathroom mirror","install mirror","mount bathroom mirror","встановити дзеркало у ванній","повісити дзеркало"],unit:"each",rate:75},
{id:"medicine_cabinet_install_each",name:"Install medicine cabinet",aliases:["install medicine cabinet","mount medicine cabinet","встановити medicine cabinet","встановити шафку з дзеркалом"],unit:"each",rate:300},
{id:"towel_warmer_install_each",name:"Install towel warmer",aliases:["install towel warmer","towel warmer installation","встановити рушникосушку","встановити towel warmer"],unit:"each",rate:250},
{id:"toilet_paper_holder_install_each",name:"Install toilet paper holder",aliases:["install toilet paper holder","mount toilet paper holder","встановити тримач туалетного паперу"],unit:"each",rate:75},
{id:"towel_bar_install_each",name:"Install towel bar",aliases:["install towel bar","mount towel bar","встановити рушникотримач","встановити towel bar"],unit:"each",rate:85},
{id:"robe_hook_install_each",name:"Install robe hook",aliases:["install robe hook","mount robe hook","встановити гачок для халата","встановити hook"],unit:"each",rate:50},
{id:"bathroom_accessories_set_each",name:"Install bathroom accessories set",aliases:["install bathroom accessories set","install bath accessories","встановити комплект аксесуарів у ванній"],unit:"each",rate:250},
{id:"outlet_new_each",name:"Install new electrical outlet",aliases:["install new outlet","add outlet","new electrical outlet","встановити нову розетку","додати розетку"],unit:"each",rate:225},
{id:"gfci_install_each",name:"Install GFCI outlet",aliases:["install gfci outlet","replace gfci outlet","gfci receptacle","встановити gfci розетку","замінити gfci"],unit:"each",rate:150},
{id:"dimmer_install_each",name:"Install dimmer switch",aliases:["install dimmer switch","replace switch with dimmer","dimmer installation","встановити димер","замінити вимикач на димер"],unit:"each",rate:125},
{id:"recessed_light_install_each",name:"Install recessed light",aliases:["install recessed light","install can light","install wafer light","встановити recessed light","встановити точковий світильник"],unit:"each",rate:150},
{id:"vanity_light_install_each",name:"Install vanity light",aliases:["install vanity light","bathroom vanity light","mirror light installation","встановити світильник над дзеркалом","встановити vanity light"],unit:"each",rate:125},
{id:"bath_fan_install_each",name:"Install bathroom exhaust fan",aliases:["install bathroom exhaust fan","install bath fan","bathroom fan installation","встановити витяжний вентилятор у ванній"],unit:"each",rate:225},
{id:"electrical_box_relocate_each",name:"Relocate electrical box",aliases:["relocate electrical box","move electrical box","move outlet box","перенести електричну коробку","перенести коробку розетки"],unit:"each",rate:200},
{id:"new_circuit_each",name:"Add new electrical circuit",aliases:["add new circuit","run new circuit from panel","dedicated circuit","додати нову електричну лінію","провести нову лінію від щита"],unit:"each",rate:650},
{id:"shower_valve_roughin_each",name:"Replace shower valve rough-in",aliases:["replace shower valve","install shower valve","shower valve rough-in","замінити душовий клапан","встановити shower valve","заміна змішувача в стіні"],unit:"each",rate:650},
{id:"shower_trim_install_each",name:"Install shower trim and handle",aliases:["install shower trim","install shower handle","shower trim kit","встановити накладку душу","встановити ручку душу"],unit:"each",rate:225},
{id:"shower_head_install_each",name:"Install shower head",aliases:["install shower head","replace shower head","встановити душову головку","замінити душову головку"],unit:"each",rate:150},
{id:"handheld_shower_install_each",name:"Install handheld shower",aliases:["install handheld shower","hand shower installation","встановити ручний душ","встановити handheld"],unit:"each",rate:225},
{id:"shower_drain_install_each",name:"Install shower drain",aliases:["install shower drain","shower drain installation","встановити душовий трап","встановити злив душу"],unit:"each",rate:350},
{id:"shower_drain_relocate_each",name:"Relocate shower drain",aliases:["relocate shower drain","move shower drain","перенести душовий злив","перенести трап"],unit:"each",rate:650},
{id:"water_lines_relocate_fixture",name:"Relocate water supply lines",aliases:["relocate water lines","move water supply lines","перенести водяні труби","перенести подачу води"],unit:"each",rate:450},
{id:"vanity_plumbing_connect_each",name:"Connect vanity plumbing",aliases:["connect vanity plumbing","connect vanity drain","connect vanity water lines","підключити сантехніку vanity","підключити тумбу до води і каналізації"],unit:"each",rate:250},
{id:"freestanding_tub_install_each",name:"Install freestanding bathtub",aliases:["install freestanding tub","freestanding bathtub installation","встановити окремостоячу ванну","монтаж freestanding tub"],unit:"each",rate:900},
{id:"bathtub_remove_each",name:"Remove bathtub",aliases:["remove bathtub","bathtub demolition","зняти ванну","демонтувати ванну"],unit:"each",rate:450},
{id:"bathtub_faucet_install_each",name:"Install bathtub faucet",aliases:["install bathtub faucet","install tub filler","встановити змішувач для ванни","встановити tub filler"],unit:"each",rate:350},
{id:"tile_remove_sqft",name:"Remove old tile",aliases:["remove old tile","tile demolition","зняти стару плитку","демонтаж плитки"],unit:"sqft",rate:5},
{id:"cement_board_install_sqft",name:"Install cement board",aliases:["install cement board","cement backer board","встановити цементну плиту","монтаж cement board"],unit:"sqft",rate:6},
{id:"uncoupling_membrane_sqft",name:"Install uncoupling membrane",aliases:["install uncoupling membrane","install ditra","uncoupling membrane","встановити ditra","розділювальна мембрана"],unit:"sqft",rate:4},
{id:"tile_waterproofing_sqft",name:"Waterproof tile area",aliases:["waterproof shower","waterproof tile area","install waterproofing membrane","гідроізоляція душу","гідроізоляція під плитку"],unit:"sqft",rate:7},
{id:"shower_pan_build_each",name:"Build and waterproof shower pan",aliases:["build shower pan","waterproof shower pan","install shower base","зробити душовий піддон","гідроізоляція піддона"],unit:"each",rate:850},
{id:"tile_grout_sqft",name:"Grout tile",aliases:["grout tile","apply grout","затерти плитку","затирка плитки"],unit:"sqft",rate:3},
{id:"tile_silicone_linear_ft",name:"Silicone tile joints",aliases:["silicone tile joints","caulk tile joints","silicone shower corners","силікон у кутах плитки","засиліконити плитку"],unit:"linear_ft",rate:5},
{id:"schluter_edge_linear_ft",name:"Install Schluter tile edge",aliases:["install schluter edge","tile edge trim","schluter trim","встановити профіль schluter","профіль для плитки"],unit:"linear_ft",rate:8},
{id:"carpet_remove_sqft",name:"Remove carpet",aliases:["remove carpet","carpet removal","зняти ковролін","демонтаж ковроліну"],unit:"sqft",rate:1.5},
{id:"lvp_remove_sqft",name:"Remove old laminate or LVP",aliases:["remove laminate","remove lvp","laminate removal","lvp removal","зняти ламінат","демонтаж ламінату","зняти вінілову підлогу"],unit:"sqft",rate:2},
{id:"subfloor_prep_sqft",name:"Concrete subfloor cleaning and preparation",aliases:["prepare concrete subfloor","remove remaining adhesive and prepare concrete subfloor","remove adhesive and prepare floor","concrete floor preparation","очистити бетонну підлогу","видалити клей і підготувати підлогу"],unit:"sqft",rate:0.8889},
{id:"localized_floor_leveling_each",name:"Localized floor patching and self-leveling",aliases:["localized floor patching and self-leveling","perform localized floor patching and self-leveling","localized leveling","patch and self level floor","локальне вирівнювання підлоги","локальне шпаклювання і самовирівнювач"],unit:"each",rate:800},
{id:"insulation_drywall_package_each",name:"Insulation and drywall installation package",aliases:["install insulation and drywall","insulation drywall tape mud and sand","install insulation in open wall cavities and hang drywall","утеплення і монтаж гіпсокартону","монтаж утеплення гіпсокартону шпаклювання і шліфування"],unit:"each",rate:1300},
{id:"paint_repaired_areas_each",name:"Prime and paint repaired areas",aliases:["prime and paint repaired areas","paint repaired drywall areas","prime and paint drywall repairs","ґрунтувати і пофарбувати відремонтовані ділянки","фарбування відремонтованих ділянок"],unit:"each",rate:450},
{id:"baseboard_shoe_package_each",name:"Install baseboards and shoe molding package",aliases:["install baseboards and shoe molding","install baseboard and shoe molding including caulk and nail holes","монтаж плінтусів і shoe molding","встановити плінтус і шузмолдинг"],unit:"each",rate:950},
{id:"paint_baseboard_shoe_package_each",name:"Paint baseboards and shoe molding package",aliases:["paint baseboards and shoe molding","paint all trim","фарбування плінтусів і shoe molding","пофарбувати плінтус і шузмолдинг"],unit:"each",rate:350},
{id:"floor_leveling_sqft",name:"Level floor with compound",aliases:["level floor","floor leveling compound","self leveling","вирівняти підлогу","самовирівнююча суміш"],unit:"sqft",rate:4.5},
{id:"underlayment_install_sqft",name:"Install flooring underlayment",aliases:["install underlayment","floor underlayment","встановити підкладку","підкладка під ламінат"],unit:"sqft",rate:1.25},
{id:"floor_transition_each",name:"Install floor transition",aliases:["install floor transition","transition strip","floor threshold","встановити перехід підлоги","перехідна планка","поріжок"],unit:"each",rate:75},
{id:"move_furniture_floor_room",name:"Move furniture for flooring",aliases:["move furniture for flooring","move furniture before floor installation","пересунути меблі для підлоги","винести меблі перед монтажем підлоги"],unit:"room",rate:100},
{id:"drywall_install_sqft",name:"Install drywall",aliases:["install drywall","new drywall installation","встановити гіпсокартон","монтаж гіпсокартону"],unit:"sqft",rate:8},
{id:"drywall_finish_sqft",name:"Tape mud and sand drywall",aliases:["tape mud and sand drywall","finish drywall","шпаклювати гіпсокартон","проклеїти і зашпаклювати гіпсокартон"],unit:"sqft",rate:6},
{id:"baseboard_install_linear_ft",name:"Install baseboards",aliases:["install baseboards","baseboard installation","встановити плінтуси","монтаж плінтусів"],unit:"linear_ft",rate:4},
{id:"door_casing_install_linear_ft",name:"Install door casing",aliases:["install door casing","door trim installation","встановити дверний наличник","монтаж дверної обналички"],unit:"linear_ft",rate:5},
{id:"quarter_round_install_linear_ft",name:"Install quarter round",aliases:["install quarter round","quarter round installation","встановити quarter round","монтаж чвертькруглого молдингу"],unit:"linear_ft",rate:3},
{id:"light_fixture_reinstall_each",name:"Reinstall light fixture",aliases:["reinstall light fixture","put light fixture back","повторно встановити світильник","поставити світильник назад"],unit:"each",rate:100},
{id:"wallpaper_remove_sqft",name:"Remove wallpaper",aliases:["remove wallpaper","wallpaper removal","зняти шпалери","демонтаж шпалер"],unit:"sqft",rate:2.5},
{id:"baseboard_remove_linear_ft",name:"Remove baseboards",aliases:["remove baseboards","baseboard removal","зняти плінтуси","демонтаж плінтусів"],unit:"linear_ft",rate:2},
{id:"drywall_remove_sqft",name:"Remove damaged drywall",aliases:["remove damaged drywall","drywall demolition","вирізати пошкоджений гіпсокартон","демонтаж гіпсокартону"],unit:"sqft",rate:4},
{id:"door_remove_each",name:"Remove interior door",aliases:["remove interior door","door removal","зняти двері","демонтувати двері"],unit:"each",rate:100},
{id:"light_fixture_remove_each",name:"Remove light fixture",aliases:["remove light fixture","light fixture removal","зняти світильник","демонтувати світильник"],unit:"each",rate:75},
{id:"protect_room_each",name:"Protect floors and furniture",aliases:["protect floors and furniture","cover floors","cover furniture","захистити підлогу і меблі","накрити підлогу","накрити меблі"],unit:"room",rate:125},
{id:"fill_nail_holes_room",name:"Fill nail holes",aliases:["fill nail holes","nail holes","закрити отвори від цвяхів","зашпаклювати отвори від цвяхів"],unit:"room",rate:75},
{id:"caulk_trim_linear_ft",name:"Caulk baseboards and trim",aliases:["caulk baseboards","caulk trim","герметизувати плінтуси","закрити щілини біля плінтусів","caulking trim"],unit:"linear_ft",rate:2},
{id:"final_cleanup_room",name:"Final cleanup",aliases:["final cleanup","jobsite cleanup","clean up room","фінальне прибирання","прибрати після роботи"],unit:"room",rate:100},
{id:"drywall_crack_linear_ft",name:"Repair drywall crack",aliases:["repair drywall crack","drywall crack","тріщина в гіпсокартоні","ремонт тріщини"],unit:"linear_ft",rate:12},
{id:"drywall_tape_repair_each",name:"Repair loose drywall tape",aliases:["repair loose drywall tape","drywall tape repair","відклеївся tape","ремонт стрічки гіпсокартону","відклеїлась стрічка"],unit:"each",rate:175},
{id:"drywall_corner_repair_each",name:"Repair damaged drywall corner",aliases:["repair drywall corner","damaged corner","пошкоджений кут гіпсокартону","ремонт кута"],unit:"each",rate:225},
{id:"water_stain_block_each",name:"Seal water stain",aliases:["seal water stain","water stain primer","пляма від води","заблокувати пляму від води","stain blocking primer"],unit:"each",rate:100},
{id:"drywall_patch_addon_minor",name:"Minor drywall patch add-on",aliases:["minor drywall patch add-on","small drywall patch with room painting","маленька латка гіпсокартону разом з фарбуванням","залатати невеликий отвір під час фарбування кімнати"],unit:"each",rate:150},
{id:"drywall_patch_addon_medium",name:"Medium drywall patch add-on",aliases:["medium drywall patch add-on","medium drywall repair with room painting","середня латка гіпсокартону разом з фарбуванням"],unit:"each",rate:225},
{id:"drywall_patch_addon_large",name:"Large drywall repair add-on",aliases:["large drywall repair add-on","replace damaged drywall with room painting","великий ремонт гіпсокартону разом з фарбуванням"],unit:"each",rate:350},
{id:"drywall_repair_standalone",name:"Standalone drywall repair visit",aliases:["standalone drywall repair","drywall repair only","окремий виїзд на ремонт гіпсокартону","тільки залатати отвір","ремонт гіпсокартону без фарбування кімнати"],unit:"each",rate:300},
{id:"paint_door_each",name:"Paint door",aliases:["paint door","paint doors","пофарбувати двері","фарбування дверей"],unit:"each",rate:150},
{id:"paint_door_frame_each",name:"Paint door frame",aliases:["paint door frame","paint door casing","пофарбувати дверну коробку","фарбування дверної коробки"],unit:"each",rate:100},
{id:"paint_baseboards_linear_ft",name:"Paint baseboards",aliases:["paint baseboards","paint trim","пофарбувати плінтуси","фарбування плінтусів"],unit:"linear_ft",rate:2.5},
{id:"paint_window_each",name:"Paint window",aliases:["paint window","paint windows","пофарбувати вікно","пофарбувати вікна","фарбування вікна","фарбування вікон"],unit:"each",rate:100},
{id:"replace_outlet_each",name:"Replace electrical outlet",aliases:["replace outlet","electrical outlet","outlet","розетка","розетки","замінити розетку"],unit:"each",rate:75},
{id:"replace_switch_each",name:"Replace light switch",aliases:["replace switch","light switch","switch","вимикач","вимикачі","замінити вимикач"],unit:"each",rate:75},
{id:"kitchen_faucet_replace",name:"Replace kitchen faucet",aliases:["kitchen faucet","кухонний кран","кран на кухні","змішувач на кухні"],unit:"each",rate:250},
{id:"bathroom_faucet_replace",name:"Replace bathroom faucet",aliases:["bathroom faucet","кран у ванній","змішувач у ванній"],unit:"each",rate:225},
{id:"bath_fan_replace",name:"Replace bathroom exhaust fan",aliases:["bath fan","exhaust fan","вентилятор у ванній","витяжний вентилятор"],unit:"each",rate:225},
{id:"ceiling_fan_replace",name:"Replace ceiling fan",aliases:["ceiling fan","стельовий вентилятор","вентилятор на стелі"],unit:"each",rate:250},
{id:"paint_walls_sqft",name:"Paint walls",aliases:["paint walls","фарбування стін","пофарбувати стіни"],unit:"sqft",rate:2.5},
{id:"paint_wall_each",name:"Paint one wall",aliases:["paint one wall","пофарбувати одну стіну"],unit:"each",rate:250},
{id:"paint_room",name:"Paint room walls",aliases:["paint room","пофарбувати кімнату"],unit:"room",rate:650},
{id:"paint_ceiling_sqft",name:"Paint ceiling",aliases:["paint ceiling","фарбування стелі","пофарбувати стелю"],unit:"sqft",rate:2.75},
{id:"lvp_install_sqft",name:"Install LVP / laminate flooring",aliases:["install lvp flooring","install laminate flooring","lvp","laminate","ламінат","вінілова підлога","монтаж ламінату"],unit:"sqft",rate:2.3333},
{id:"floor_tile_sqft",name:"Install floor tile",aliases:["floor tile","плитка на підлогу"],unit:"sqft",rate:18},
{id:"wall_tile_sqft",name:"Install wall tile",aliases:["wall tile","плитка на стіну"],unit:"sqft",rate:22},
{id:"toilet_replace",name:"Remove and install toilet",aliases:["replace toilet","замінити унітаз","встановити унітаз"],unit:"each",rate:180},
{id:"vanity_install",name:"Install bathroom vanity",aliases:["install vanity","встановити тумбу","тумба у ванну"],unit:"each",rate:350},
{id:"drywall_minor",name:"Minor drywall repair",aliases:["drywall repair","ремонт гіпсокартону","шпаклювання"],unit:"each",rate:250},
{id:"door_install",name:"Install interior door",aliases:["interior door","міжкімнатні двері","встановити двері"],unit:"each",rate:350},
{id:"baseboard_install",name:"Install baseboard",aliases:["baseboard","плінтус"],unit:"linear_ft",rate:3.0645},
{id:"garbage_disposal_replace",name:"Replace garbage disposal",aliases:["garbage disposal","подрібнювач відходів"],unit:"each",rate:250},
{id:"light_fixture_replace",name:"Replace light fixture",aliases:["light fixture","світильник","люстра"],unit:"each",rate:125}
];

const added:PriceRule[]=[
{id:"wood_frame_sqft",name:"Каркас 2×4, площа однієї сторони",aliases:["wood stud framing","каркас стіни"],unit:"sqft",rate:3.72,rateMin:2.38,rateMax:5.06},
{id:"insulation_r19_sqft",name:"Монтаж утеплення R-19",aliases:["R19 batt insulation","утеплення"],unit:"sqft",rate:1.10,rateMin:.71,rateMax:1.50},
{id:"lvp_stair_each",name:"Монтаж LVP на сходинку",aliases:["lvp stair","ламінат на сходи"],unit:"each",rate:60,rateMin:45,rateMax:75},
{id:"crown_molding_lf",name:"Монтаж crown molding",aliases:["crown molding","стельовий плінтус"],unit:"linear_ft",rate:4.50,rateMin:3,rateMax:6},
{id:"tile_patch_each",name:"Заміна окремої плитки",aliases:["replace single tile","заміна плитки"],unit:"each",rate:112.5,rateMin:75,rateMax:150},
{id:"tile_regrout_lf",name:"Перезатирання швів плитки",aliases:["regrout joints","перезатирка швів"],unit:"linear_ft",rate:4.50,rateMin:3,rateMax:6},
{id:"shower_valve_trim_each",name:"Душовий клапан і trim, відкритий доступ",aliases:["shower valve and trim open access","клапан і накладка душу"],unit:"each",rate:375,rateMin:300,rateMax:450},
{id:"light_new_wiring_each",name:"Монтаж світильника з новою проводкою",aliases:["light new wiring","світильник нова проводка"],unit:"each",rate:275,rateMin:200,rateMax:350},
{id:"bath_fan_new_duct_each",name:"Вентилятор з новим повітропроводом",aliases:["bath fan new duct","вентилятор новий повітропровід"],unit:"each",rate:450,rateMin:350,rateMax:550},
{id:"exterior_door_each",name:"Монтаж вхідних дверей",aliases:["exterior door","вхідні двері"],unit:"each",rate:475,rateMin:350,rateMax:600},
{id:"storm_door_each",name:"Монтаж storm door",aliases:["storm door","зовнішні захисні двері"],unit:"each",rate:200,rateMin:150,rateMax:250},
{id:"door_adjust_each",name:"Регулювання дверей",aliases:["adjust door","регулювання дверей"],unit:"each",rate:87.5,rateMin:50,rateMax:125},
{id:"door_handle_each",name:"Ручка в готові отвори",aliases:["door handle existing holes","дверна ручка"],unit:"each",rate:55,rateMin:35,rateMax:75},
{id:"shelf_ready_each",name:"Монтаж готової полиці до 4 ft",aliases:["install shelf","монтаж полиці"],unit:"each",rate:70,rateMin:40,rateMax:100},
{id:"cabinet_handle_each",name:"Монтаж меблевої ручки",aliases:["cabinet handle","меблева ручка"],unit:"each",rate:7.50,rateMin:5,rateMax:10},
{id:"cabinet_remove_each",name:"Демонтаж шафки",aliases:["remove cabinet","демонтаж шафки"],unit:"each",rate:37.50,rateMin:25,rateMax:50},
{id:"cleanup_person_hour",name:"Винесення й прибирання, людино-година",aliases:["cleanup carry debris","винести сміття прибирання"],unit:"hour",rate:55,rateMin:50,rateMax:60},
{id:"paint_window_trim_lf",name:"Фарбування віконної лиштви",aliases:["paint window trim","фарбування віконної лиштви"],unit:"linear_ft",rate:3.72,rateMin:2.38,rateMax:5.05},
{id:"paint_sill_each",name:"Фарбування підвіконня до 4 ft",aliases:["paint sill","фарбування підвіконня"],unit:"each",rate:40,rateMin:30,rateMax:50},
{id:"paint_shoe_lf",name:"Фарбування shoe molding",aliases:["paint shoe molding","фарбування шузмолдинг"],unit:"linear_ft",rate:1.25,rateMin:1,rateMax:1.50},

{id:"prime_surface_sqft",name:"Ґрунтування, один шар",aliases:["ґрунтування","prime surface"],unit:"sqft",rate:.40,rateMin:.30,rateMax:.50},
{id:"skim_coat_sqft",name:"Суцільне шпаклювання",aliases:["skim coat","суцільне шпаклювання"],unit:"sqft",rate:.94,rateMin:.85,rateMax:1.03},
{id:"drywall_finish_joint_lf",name:"Стрічка, шпаклівка, шліфування стиків",aliases:["finish drywall joints","шпаклювання стиків"],unit:"linear_ft",rate:1.50,rateMin:1.36,rateMax:1.65},
{id:"drywall_crack_each",name:"Ремонт невеликої тріщини",aliases:["repair small crack","ремонт тріщини"],unit:"each",rate:75,rateMin:50,rateMax:100},
{id:"subfloor_osb_sqft",name:"Монтаж OSB",aliases:["OSB subfloor","монтаж осб"],unit:"sqft",rate:2.65,rateMin:1.70,rateMax:3.60},
{id:"waterproof_board_seams_lf",name:"Герметизація швів гідроізоляційних плит",aliases:["waterproof board seams","герметизація швів плит"],unit:"linear_ft",rate:3,rateMin:2.50,rateMax:3.50},
{id:"sheet_membrane_sqft",name:"Монтаж листової гідроізоляційної мембрани",aliases:["sheet waterproof membrane","листова мембрана"],unit:"sqft",rate:4.20,rateMin:3.63,rateMax:4.78},
{id:"prefab_shower_pan_sqft",name:"Монтаж стандартного готового душового піддона",aliases:["prefab shower pan","готовий душовий піддон"],unit:"sqft",rate:22.50,rateMin:22.50,rateMax:22.50,laborNote:"$300 / 13.333 sq ft для прикладу 60×32 in. Для іншого піддона перевір ставку."},
{id:"prefab_niche_each",name:"Монтаж готової ніші до 12×24 in, ущільнення",aliases:["prefab niche","готова ніша"],unit:"each",rate:137.5,rateMin:100,rateMax:175},
{id:"prefab_bench_each",name:"Монтаж готової лавки до 36 in, ущільнення",aliases:["prefab shower bench","готова лавка"],unit:"each",rate:200,rateMin:150,rateMax:250},
{id:"standard_shower_door_each",name:"Монтаж стандартних поворотних душових дверей",aliases:["standard pivot shower door","стандартні душові двері"],unit:"each",rate:299.5,rateMin:192,rateMax:407},
{id:"acrylic_tub_each",name:"Монтаж акрилової ванни",aliases:["acrylic tub","акрилова ванна"],unit:"each",rate:475,rateMin:350,rateMax:600},
{id:"cabinet_box_each",name:"Монтаж зібраної шафки",aliases:["assembled cabinet","монтаж шафки"],unit:"each",rate:125,rateMin:100,rateMax:150},
{id:"paint_trim_lf",name:"Фарбування лиштви",aliases:["paint casing","фарбування лиштви"],unit:"linear_ft",rate:2.1,rateMin:1.34,rateMax:2.86},
{id:"paint_cabinet_sqft",name:"Фарбування шаф, площа поверхні",aliases:["paint cabinets","фарбування шаф"],unit:"sqft",rate:7.26,rateMin:4.65,rateMax:9.87}
];
export const defaults:PriceRule[]=[...legacy.map(approvedRule).filter(p=>!p.laborNote?.startsWith("Стара базова")||p.id==="bathroom_mirror_install_each"),...added.map(p=>({...p,catalogVersion:2,materialStatus:"unknown" as const,laborNote:p.laborNote??"Узгоджена ставка роботи для 60171; матеріали окремо."}))];
export function applyApprovedCatalog(current:PriceRule[]):PriceRule[]{
 const ids=new Set([...defaults,...legacy].map(p=>p.id));
 return [...defaults.map(p=>({...p,aliases:[...p.aliases]})),...current.filter(p=>!ids.has(p.id))];
}

const scopeNotes:Record<string,string>={
 wall_tile_sqft:"Робота включає монтаж backer, укладання й затирку: не додавай ці роботи повторно.",
 vanity_backsplash_sqft:"Робота включає монтаж backer, укладання й затирку: не додавай ці роботи повторно.",
 vanity_remove_each:"Вже відключена тумба; відключення й вивезення окремо.",
 bathtub_remove_each:"Звичайна ванна, не чавунна; вивезення окремо.",
 vanity_install:"Встановлення тумби до 48 in; сантехніка окремо.",
 floor_transition_each:"Поріг до 4 ft.",
 paint_door_each:"Фарбування дверного полотна з двох боків.",
 drywall_patch_addon_minor:"Латка до 6 in, без фарбування.",
 drywall_patch_addon_medium:"Латка 6–12 in, без фарбування.",
 door_install:"Стандартні міжкімнатні prehung двері.",
 cement_board_install_sqft:"Не додавай, якщо монтаж backer уже включено до плиткових робіт."
};
for(const rule of defaults)if(scopeNotes[rule.id])rule.laborNote+=" "+scopeNotes[rule.id];

for(let n=0;n<defaults.length;n++)defaults[n]=materialDefaults(defaults[n]);

const mirror=defaults.find(p=>p.id==="bathroom_mirror_install_each");if(mirror)mirror.laborNote="Узгоджена базова ставка монтажу готового дзеркала: $75. Дзеркало й кріплення окремо.";
