export type Unit="each"|"sqft"|"hour"|"linear_ft"|"room";
export type Item={
  id:string;
  serviceId:string;
  description:string;
  quantity:number;
  unit:Unit;
  unitPrice:number;
  laborScope?:string;
  materialBasisQuantity?:number;
  laborMin?:number;
  laborMax?:number;
  materialRate?:number;
  materialMin?:number;
  materialMax?:number;
  materialStatus?:"unknown"|"partial"|"priced"|"none";
  customerMaterials?:boolean;
  materialNote?:string;
  note?:string;
  confidence?:number;
};
export type EstimateStatus="draft"|"sent"|"viewed"|"accepted";
export type Estimate={
  id:string;
  client:string;
  project:string;
  address:string;
  items:Item[];
  discount:number;
  tax:number;
  deposit:number;
  createdAt:string;
  preliminary?:boolean;
  measurementNotes?:string;
  shareToken?:string;
  status?:EstimateStatus;
};
export type PriceRule={
  id:string;
  name:string;
  aliases:string[];
  unit:Unit;
  rate:number;
  rateMin?:number;
  rateMax?:number;
  category?:string;
  materialRate?:number;
  materialMin?:number;
  materialMax?:number;
  materialStatus?:"unknown"|"partial"|"priced"|"none";
  materialNote?:string;
  laborNote?:string;
  catalogVersion?:number;
};
